### ISSUE TITLE
Question: Plans to port all unit tests to iOS?

### ISSUE THREAD

**Issue by oscarbg** [ConfettiFX/The-Forge#10]
Hi,
I see 01_transformation_ios sample but the others aren't avaiable on iOS right now..
is that due to Metal limitations on iOS vs on desktop or just is a start and there are plans to port it?
thanks..

**Comment by wolfgangfengel** [comment]
We officially do not support iOS in the moment :-) At some point, we will. Depends on how much time we can allocate for this in the next few weeks. As soon as iOS is fully supported we will commit the code ... and write a release note.
