### ISSUE TITLE
Multi-Monitor Support?

### ISSUE THREAD

**Issue by mgsim** [ConfettiFX/The-Forge#101]
What is the best way to set up rendering to multiple full-screen monitors using a single GPU adapter in The Forge? Do you have an example that uses multi-monitor?

**Comment by wolfgangfengel** [comment]
Hey mgsim, what is your usage case? Obviously, you can plug two monitors in your GPU and you can run them ... but this is probably not what you are asking.

**Comment by boberfly** [comment]
Hi @mgsim 
I was able to use The-Forge with GLFW: https://www.glfw.org/ which does let you spawn multiple windows. From there I would associate each one with its own swapchain by passing the window handle to the descriptor struct and handle it much like you would with a native API from there. (GLFW lets you create these windows without OpenGL contexts, it works with any API that supports the native OS window handle). Alternatively SDL2 could be used.

**Comment by mgsim** [comment]
@wolfgangfengel My particular use case is for rendering to a custom 3D stereoscope where each eye receives a full-screen render image from a different viewpoint. In addition I need to support even more windows/monitors for additional unrelated drawing or debug views with a free camera. I could use a distinct GPU adapter for each eye, but I'm particularly interested in the usage of The Forge API with multi-monitor where there is only one GPU available.

@boberfly Thank you for your comments. I am currently using an identical setup to you. I use GLFW for generating multiple OS windows with no context and use GLFW's native header to retrieve the native window handles to pass to The Forge. This works perfectly and I have multiple windows to which I can render, but I am looking for best practices regarding the usage of The Forge for rendering to these windows. I'm concerned with the most efficient way to render to multiple monitors regarding the usage of threads, single or multiple command queues, command lists, and descriptor heaps. I'd like to duplicate as few resources as possible.

**Comment by wolfgangfengel** [comment]
We used The Forge for StarVR and I know we used it in other AR / VR environments. So I assume it is possible. I ask the guys who worked on those projects ... and get back to you.

**Comment by mgsim** [comment]
@wolfgangfengel That's good news. I look forward to hearing your response. I think adding a multi-window/multi-monitor example to the unit tests would be immensely helpful too.

**Comment by mgsim** [comment]
@wolfgangfengel Did the guys who worked on StarVR or the other AR / VR environments with The Forge get back to you with any best practices? I'm still interested in learning this. Thanks.

**Comment by mgsim** [comment]
@wolfgangfengel Any forward progress on this issue? I'm still very interested. I'd be happy to set up a meeting to discuss this with you at SIGGRAPH in L.A. if you will be attending this year. Thanks.

**Comment by wolfgangfengel** [comment]
I think we have now multi-monitor support in the new window example. Let me know if this is what you were looking for.

**Comment by wolfgangfengel** [comment]
@mgsim can I close this issue?

**Comment by mgsim** [comment]
Yes. Thank you.
________________________________
