### ISSUE TITLE
Question: Is support for OpenGL/GLSL planned ?

### ISSUE THREAD

**Issue by rathnavels** [ConfettiFX/The-Forge#102]
Hello,

I haven't tried Forge yet.  But it seems very intriguing to me.  Wondering if you are planning to support OpenGL/GLSL 4.0+ as I do not see it in the supported APIs on any platform.  Could you please clarify this?

Thanks in advance!

**Comment by wolfgangfengel** [comment]
That's not planned. Occasionally we have customers who request additional APIs like DirectX 11. So far no one asked for OpenGL support.
