### ISSUE TITLE
Tiled resources / reserve resources support ?

### ISSUE THREAD

**Issue by gjaegy** [ConfettiFX/The-Forge#104]
Hi,

Our current D3D11-based engine is using tiled resources. 
Does The Forge provide any abstration layer for its abstract equivalent (reserved resources in D3D12, etc.) ?

Thanks a lot!
Cheers,
Greg

**Comment by wolfgangfengel** [comment]
Hi Greg,
this is our No. 1 priority feature that we want to add. Can't promise when it is in there but probably very soon.

Have a great day,
- Wolfgang

**Comment by wolfgangfengel** [comment]
Took longer than expected :-) The new Sparse Virtual Texture example should cover that?

**Comment by gjaegy** [comment]
Hi Wolfgang,

this is good news, thanks for the hard work and sharing the news. I'll have a look at this !

Cheers,
Greg
