### ISSUE TITLE
There is not target for iOS in 15_Transparent

### ISSUE THREAD

**Issue by ldbfrank** [ConfettiFX/The-Forge#107]

**Comment by ldbfrank** [comment]
悄悄问句：人儿呢？

**Comment by AntoineConffx** [comment]
We haven't added ROG support on iOS yet and that's why it's missing.

**Comment by ldbfrank** [comment]
oh, I really look forward to seeing the effects of OIT, my MBP is not working, and now iOS is not working. :-(
