### ISSUE TITLE
15_Transparency can not run on MacOS

### ISSUE THREAD

**Issue by ldbfrank** [ConfettiFX/The-Forge#108]
Hi,
I tried 15_Transparency on my Mac Book Pro (2015), it run error following:
![未标题-1副本副本](https://user-images.githubusercontent.com/758540/57055548-bc510580-6cce-11e9-89e6-20e42b59cb6a.jpg)
Is it not supported on my hardware?

**Comment by wolfgangfengel** [comment]
Do you use XCode and macOS version as described in the Readme? I believe we do not test on MacBook Pro (2015), so maybe the older Intel GPU can't support it?
Can you provide us with the Model number ... this is the number that we mention in the macOS requirement section for the machines we are testing on.

**Comment by wolfgangfengel** [comment]
Here is the requirement list:
macOS Requirements:
macOS Mojave 10.14.4 beta (18E174f)

Xcode 10.2 beta (10P82s)

The Forge is currently tested on the following macOS devices:

iMac with AMD RADEON 560 (Part No. MNDY2xx/A)
iMac with AMD RADEON 580 (Part No. MNED2xx/A)
MacBook Pro 13 inch (MacBookPro13,2)
Macbook Pro 13 inch (MacbookPro14,2)
In the moment we do not have access to an iMac Pro or Mac Pro. We can test those either with Team Viewer access or by getting them into the office and integrating them into our build system. We will not test any Hackintosh configuration.

**Comment by ldbfrank** [comment]
Hi,
Following is my MBP info:
![屏幕快照 2019-05-02 下午4 31 51副本](https://user-images.githubusercontent.com/758540/57064534-2ed6db00-6cf9-11e9-9725-1af4a3693ece.png)

**Comment by ldbfrank** [comment]
It seems the older Intel GPU can't support it.  ^_^
