### ISSUE TITLE
MipMapMode always the same for addSampler in Vulkan

### ISSUE THREAD

**Issue by jesta88** [ConfettiFX/The-Forge#11]
https://github.com/ConfettiFX/The-Forge/blob/d83ecf995ec417bd47566ec9555920be5fd94a9d/Common_3/Renderer/Vulkan/Vulkan.cpp#L2306

This should be assigned the Vk-translated value of the mipMapMode parameter.

**Comment by manaskulkarni786** [comment]
Thanks for pointing out. It's now fixed
