### ISSUE TITLE
RenderDoc compatibility with SM6+

### ISSUE THREAD

**Issue by jdswebb** [ConfettiFX/The-Forge#110]
Hi,

Using the latest RenderDoc release (1.4) I'm not able to launch TF samples if the shader model is set to 6_0 or greater.

There is an assert on calling EnableExperimentalShaderModels() but this is just a symptom of the problem. The log reveals a bit more:

>[ Tue May  7 09:48:18 2019 ] INFO: Opened log file E:/Repos/The-Forge/Examples_3/Common/17_EntityComponentSystem.log
[ Tue May  7 09:48:19 2019 ] INFO: [openWindow] Created window app 17_EntityComponentSystem
[ Tue May  7 09:48:19 2019 ] INFO: [AddDevice] GPU[0] detected. Vendor ID: 10de, Revision ID: a1, GPU Name: NVIDIA GeForce RTX 2080 Ti
[ Tue May  7 09:48:19 2019 ] INFO: [AddDevice] GPU[0] is selected as default GPU
[ Tue May  7 09:48:19 2019 ] INFO: [AddDevice] Name of selected gpu: NVIDIA GeForce RTX 2080 Ti
[ Tue May  7 09:48:19 2019 ] INFO: [AddDevice] Vendor id of selected gpu: 0x10de
[ Tue May  7 09:48:19 2019 ] INFO: [AddDevice] Model id of selected gpu: 0x1e07
[ Tue May  7 09:48:19 2019 ] INFO: [AddDevice] Revision id of selected gpu: 0xa1
[ Tue May  7 09:48:19 2019 ] ERROR: [initRenderer] Hardware does not support Shader Model 6.0

The hardware obviously does support SM6 and the sample launches fine without RenderDoc.

In my own app I have my own DX12 backend as well as TF and I can launch with that backend using SM6+ without issue.

Thanks

**Comment by jdswebb** [comment]
I had originally reported this as happening in PIX by mistake - the crash actually happens with RenderDoc. With PIX the sample runs successfully!

**Comment by wolfgangfengel** [comment]
Hi,
thanks a lot for this! We are avid users of RenderDoc ... we even extend it occasionally for customers, we are going to fix this. Can't say if it is the next release or one after ... but expect a fix soon.

Have a great day,
- Wolfgang

**Comment by wolfgangfengel** [comment]
Should be fixed. Is it?

**Comment by jdswebb** [comment]
Verified fixed, thanks :)
