### ISSUE TITLE
cmdBindDescriptors performance issue (DX12)

### ISSUE THREAD

**Issue by jdswebb** [ConfettiFX/The-Forge#112]
I've been updating from an older version of TF to the latest one it seems there is a performance issue with the new DescriptorBinder system. The line in the screenshot now dominates runtime, and my CPU frame latency has increased from 0.8ms to 9ms.

![image](https://user-images.githubusercontent.com/5884019/57489808-1e050700-72af-11e9-8117-b24d9b6c0a3b.png)

I am calling cmdBindDescriptors thousands of times per frame, but I think this should be within the bounds of expected use.

I can try and dig into what's going on myself if it would be helpful.

**Comment by wolfgangfengel** [comment]
Just to make sure: did you read the description how the descriptor system works? It is on the Wiki page.

When you compare 0.8 ms to 9 ms did you compare the old and the new TF version? I assume you didn't change the shaders because there are four different update frequencies for descriptors and they were the same?

Let me ask Jesus to check this out ... do you have a repo case in case we need one?

**Comment by wolfgangfengel** [comment]
This is btw. really an interesting issue. In case we overlooked something we really need to fix that.

On a separate note: we have an internal support channel in which all the developers of this framework are and a number of users. I believe there are currently > 30 people. If you send me your skype id I would like to add you to this. We would value your feedback and fix things before they are on GitHub. Also if you need changes for your integration we could discuss them there.

**Comment by jdswebb** [comment]
Thanks, I've emailed you my Skype IDs.

I have read about the new descriptor system and I'm hopefully using it correctly! I've attached a hacked version of the 01_Transformations example demonstrates the hotspot: [01_Transformations.zip](https://github.com/ConfettiFX/The-Forge/files/3165745/01_Transformations.zip)


![image](https://user-images.githubusercontent.com/5884019/57515928-a3b6a000-730b-11e9-910c-a6b977ce0e50.png)

Hope this helps!
