### ISSUE TITLE
How to build a sample with Visual Studio?

### ISSUE THREAD

**Issue by johannesugb** [ConfettiFX/The-Forge#114]
Sorry for the basic question, but it is not obvious how to do it, so:
How can I build and run a sample application? I have run `PRE_BUILD.bat`, but what do I have to do afterwards?

It installs a Visual Studio extension, but what does that do? I can not find any entry in the Visual Studio menues and there are no project templates? What do I have to do after `PRE_BUILD.bat` in order to get a Visual Studio project of a sample application which I can build and run?

**Comment by jdswebb** [comment]
There are Visual Studio projects/solutions under:  The-Forge/Examples_3/Unit_Tests/PC Visual Studio 2017/

**Comment by wolfgangfengel** [comment]
Did you get it up and running?

**Comment by johannesugb** [comment]
Ah, yes. They compile and run fine! :) 
Sorry for bothering you. (I wasn't expecting the sample applications in a solution named "Unit_Tests".)
