### ISSUE TITLE
Assert while profiling

### ISSUE THREAD

**Issue by lua9520** [ConfettiFX/The-Forge#121]
Hello, Toggle the Micro Profiler in the UI panel.And mode->detailed, then click Pause.It will assert at  
```
ProfileGetGpuTickReference(__int64` * pOutCpu, __int64 * pOutGpu) Line 3163
```
Also i see a todo tag here.
```
// TODO(AITOR): Need to figure out when this is used
```
I don`t know what this is meaning. Maybe don`t know why the code will run here or something else. If this issue is useless.please close it.If not, I can offer more information if needed.

**Comment by AitorConffx** [comment]
Hi lua9520,

Removing the assert should get rid of the issue. Even if the function is unimplemented, the output of the profiling won't change so there should be no change at all. However, we will provide the implementation as soon as we can.

Thank you for your help and sorry for the inconvenience.

Aitor

**Comment by lua9520** [comment]
Thanks,I get your point. I know this could be ignored in the code. I just want to make sure if this is on your todo list or need more information, because It said need to figure out when this is used.If it`s in your todo lists,just close this issue. If not, I could provide more infomation.Now I think you can close this issue. 
Thanks again.

**Comment by wolfgangfengel** [comment]
That should be fixed now.
