### ISSUE TITLE
How do i build The Forge?

### ISSUE THREAD

**Issue by AlastairGrowcott** [ConfettiFX/The-Forge#123]
I cannot find any build instructions. I am building on Linux. I have installed CodeLite, run the PRE_BUILD.command script and when I try to run PyBuild.py I get hundreds of errors, starting with:

Executing command: codelite-make -w VisibilityBuffer.workspace -p VisibilityBuffer -c Debug

[ERROR ] Could not load build settings configuration object (Version 2.1 / build_settings.xml)

Executing command: make -s

make: *** No targets specified and no makefile found. Stop.
('FAILED BUILDING ', 'VisibilityBuffer.workspace/VisibilityBuffer', 'Debug')

I have no idea how to use CodeLite but after realising it was an IDE (ugh!) I ran it, did the setup wizard and tried to open an existing workspace - there isn't one in the top level directory.

What wouldn't I give to just see a CMakeLists.txt file in the top level directory!

**Comment by wolfgangfengel** [comment]
Just use the solution file. Can you find it?

**Comment by wolfgangfengel** [comment]
You want to look into this folder: 

https://github.com/ConfettiFX/The-Forge/tree/master/Examples_3/Visibility_Buffer/UbuntuCodelite

**Comment by wolfgangfengel** [comment]
If you bump into problems, let me know, I can also make you part of a support forum. Please note we only test what is in our Linux requirement list ...

**Comment by AlastairGrowcott** [comment]
Thanks. I'll try to find time to give this a go today.

Am i right in thinking that this workspace will build just the engine and one example?

Is there any documentation on the API for this engine?

I'd also like to extract the libraries and headers from the build tree to use in my own project. Is there some sort of "install" build target for this?

**Comment by AlastairGrowcott** [comment]
That built and ran fine.

The cushions on the upper terrace fuzz a bit like white noise on an analogue TV when the camera is moving, but otherwise that is a pretty awesome demo.

**Comment by wolfgangfengel** [comment]
Great! I will close this then.
