### ISSUE TITLE
Missing KeyKpAdd mapping

### ISSUE THREAD

**Issue by srojasfredini** [ConfettiFX/The-Forge#124]
Just noticed that there is a mapping missing in 

ThirdParty\OpenSource\gainput\lib\source\gainput\keyboard\GainputInputDeviceKeyboardWin.h

The mapping missing is

dialect_[VK_ADD] = KeyKpAdd;

I'm attaching a patch with the small fix.

[MissingMapping.zip](https://github.com/ConfettiFX/The-Forge/files/3384443/MissingMapping.zip)

**Comment by wolfgangfengel** [comment]
Thank you! This is very nice of you! We will add this to the next release. In the meantime, if you are interested in spending more time with the cutting edge of the code base, I could invite you to our internal
Gitlab server where all the magic happens. Drop me a note ...

**Comment by srojasfredini** [comment]
Thanks for your answer. That invite would be great :) . I've got another fix here somewhere... I'll check if it still an issue in latest and drop you a patch in case it is.

**Comment by wolfgangfengel** [comment]
I would need your e-mail address for this.

**Comment by srojasfredini** [comment]
Sure, srojasfredini@live.com.ar.

**Comment by wolfgangfengel** [comment]
Fixed with Release 1.40
