### ISSUE TITLE
25 Skinning can't run on Macbook Pro.

### ISSUE THREAD

**Issue by ldbfrank** [ConfettiFX/The-Forge#127]
The 25 Skinning run in error like the picture uploaded from 1.29 to now.
![屏幕快照 2019-07-17 下午12 30 46](https://user-images.githubusercontent.com/758540/61347314-fcb42e80-a88e-11e9-9329-5ea386ebe971.png)

**Comment by wolfgangfengel** [comment]
Thanks for sending this in. We can't test on Macbook Pro because we don't have one but we had a similar bug with the Mac Pro that we just fixed ... I ask around ...

**Comment by wolfgangfengel** [comment]
Oh wait a second you mean Macbook Pro not iMac Pro ... that is strange. We test on MacBook Pro ... what OS and XCode version do you use?

**Comment by ldbfrank** [comment]
MacOS Mojave: 10.14.5
Xcode: 10.2.1
I have commented lines 1546 - 1566 in file The-Forge/Common_3/Renderer/MetalRenderer.mm for running on Macbook Pro. ^_^ Because these code judge if the GPU is GPU_PRESET_LOW.
![屏幕快照 2019-07-18 上午1 54 52](https://user-images.githubusercontent.com/758540/61398650-05dce400-a8ff-11e9-9bf3-eb5a8ef8fc0d.png)

**Comment by ldbfrank** [comment]
Oh, PS: The code I am testing is 1.30 source code zip from Releases page.

**Comment by manaskulkarni786** [comment]
Thank you for pointing this out. It should be fixed in the next release.
