### ISSUE TITLE
The DepthStateDesc.mDepthTest is ignored on the Metal backend

### ISSUE THREAD

**Issue by DeanoC** [ConfettiFX/The-Forge#128]
You have to set the CMP to ALWAYS to get the effect you'd expect from depth test = false on Mac Metal (probably iOS as well but not tested).
To test create a DepthState with
mDepthTest = false;
mDepthFunc = CMP_NEVER;
and render something
You expect it to render as even tho func is never, the test should be off but it won't render. Change mDepthFunc to CMP_ALWAYS and its renders.

**Comment by wolfgangfengel** [comment]
Resolved with release 1.33.
