### ISSUE TITLE
[Vulkan] Invalid function pointer name passed for vkCmdDrawIndirectCountAMD

### ISSUE THREAD

**Issue by jesta88** [ConfettiFX/The-Forge#13]
https://github.com/ConfettiFX/The-Forge/blob/f6d52d7f044192b3702d1f7814736ebcb859bda1/Common_3/Renderer/Vulkan/Vulkan.cpp#L4763

The name of the function should be "vkCmdDrawIndirectCountAMD" instead of "vkCmdIndirectCountAMD".

**Comment by wolfgangfengel** [comment]
That should be fixed now. Can you close this issue?
