### ISSUE TITLE
Vulkan and D3D12 backend set sampler maxLod to zero for nearest mipmap mode

### ISSUE THREAD

**Issue by DeanoC** [ConfettiFX/The-Forge#130]
Both the Vulkan and D3D12 backend, force a maxLOD of 0 when point sampled mipmap filtering is used. This is incorrect its perfectly useful for a shader or lodBias sampler state when using point sampled mipmaps.

For the D3D12 backed (very similar for Vulkan) this line
```pSampler->mDxSamplerDesc.MaxLOD = ((pDesc->mMipMapMode == MIPMAP_MODE_LINEAR) ? D3D12_FLOAT32_MAX : 0.0f);```
should be
```pSampler->mDxSamplerDesc.MaxLOD = D3D12_FLOAT32_MAX;```

**Comment by wolfgangfengel** [comment]
Resolved with release 1.33.
