### ISSUE TITLE
Vulkan sampler set the anistropy flag to false always.

### ISSUE THREAD

**Issue by DeanoC** [ConfettiFX/The-Forge#131]
The vulkan backend always sets the sampler anistropyEnable flag to false, should probably be set to true whenever maxAnistropy is > 0.0
Changing it to
```add_info.anisotropyEnable = (pDesc->mMaxAnisotropy > 0.0f)? VK_TRUE : VK_FALSE;```
should fix it.

**Comment by wolfgangfengel** [comment]
Solved with Release 1.33.
