### ISSUE TITLE
Integrating The Forge with existing projects?

### ISSUE THREAD

**Issue by hydexon** [ConfettiFX/The-Forge#133]
I apologize about this, but what needs The Forge to be used as an third-party dependency for an project?, since your build system is a bit confusing for me. I've seen you just can copy the Common_3 directory and omit the others, to my project and setup my build system to build it as an Shared/Static library?, it this correct?..

Thanks.

**Comment by jdswebb** [comment]
Yes, that's roughly what you need to do. Integration can be a bit painful as TF is kind of monolithic. You might find these two projects useful as well (even if just for inspiration):

https://github.com/boberfly/The-Forge-Lite
https://github.com/DeanoC/The-Forge

**Comment by hydexon** [comment]
Despite i've studying the codebase, they use python scripts to generate DLL interfaces of the rendering system.

**Comment by wolfgangfengel** [comment]
You want to continue this discussion in the Discord channel ...
