### ISSUE TITLE
Terrain example + shadows?

### ISSUE THREAD

**Issue by VinnyVicious** [ConfettiFX/The-Forge#139]
Is there an example project with heightmap terrain and shadows?

**Comment by VinnyVicious** [comment]
Should I understand this as "no support planned"?

**Comment by dsrour** [comment]
There is no example with terrain rendering at the moment.  We do have a shadow playground example.  A terrain sample might come in the future, but this isn't a major priority at the moment.  If you'd like to contribute one, that would be awesome :).
