### ISSUE TITLE
[Vulkan] IndirectCommnadsLayout never created in addIndirectCommandSignature

### ISSUE THREAD

**Issue by jesta88** [ConfettiFX/The-Forge#14]
https://github.com/ConfettiFX/The-Forge/blob/f6d52d7f044192b3702d1f7814736ebcb859bda1/Common_3/Renderer/Vulkan/Vulkan.cpp#L4845

At the end of the function, should call vkCreateIndirectCommandsLayoutNVX() with the previously filled VkIndirectCommandsLayoutCreateInfoNVX.

**Comment by wolfgangfengel** [comment]
That should be fixed now. We removed the NVX commands because we didn't use them. Can you close this issue?
