### ISSUE TITLE
[Vulkan] Invalid max semaphore count in queuePresent

### ISSUE THREAD

**Issue by jesta88** [ConfettiFX/The-Forge#15]
https://github.com/ConfettiFX/The-Forge/blob/f6d52d7f044192b3702d1f7814736ebcb859bda1/Common_3/Renderer/Vulkan/Vulkan.cpp#L3842

Should be waitSemaphoreCount = waitSemaphoreCount > MAX_PRESENT_WAIT_SEMAPHORES ? MAX_PRESENT_WAIT_SEMAPHORES : waitSemaphoreCount;

**Comment by manaskulkarni786** [comment]
You are right. That looks like a typo. Expect it to be fixed in next release

**Comment by wolfgangfengel** [comment]
That should be fixed now. Can you close this issue?
