### ISSUE TITLE
Benchmark support?

### ISSUE THREAD

**Issue by michaellarabel** [ConfettiFX/The-Forge#156]
Hi, just wondering if The-Forge has any support (or plans) for any integrated command-line driven benchmarking of your rendering code? A setup that could be automated like with your new path tracer test for showing various performance metrics afterwards dumped to the CLI or log file, etc?

Thanks,
Michael

**Comment by wolfgangfengel** [comment]
Hi Michael,
that is a great idea! We should do this. Let me know what you need and how you want to use it and we make it happen. I assume we target Linux :-) 

Please contact me at wolf @ conffx.com
Just leave out the spaces :-)

Have a great day,
- Wolfgang

**Comment by wolfgangfengel** [comment]
We are working on it ... we might ship it with the next release.

**Comment by michaellarabel** [comment]
Hi just checking if benchmark support is still being worked on or happens to be in the new 1.40 release? (Hadn't seen it in the notes so figured I would check.) Thanks!

**Comment by wolfgangfengel** [comment]
Yes, we are working on it and wanted to contact you. We are hoping to have it finished this week or next week. I get you in touch with the person who is working on it.

**Comment by wolfgangfengel** [comment]
Hey @michaellarabel please let me know if I can close this.

**Comment by michaellarabel** [comment]
Hi @wolfgangfengel yes that latest build looked good. I didn't have the time to do any thorough multi-GPU comparison tests yet but hope to do for the next release.

**Comment by wolfgangfengel** [comment]
Let us know if you bump into problems and we fix them ...
