### ISSUE TITLE
EntityComponentSystem example has bad FPS

### ISSUE THREAD

**Issue by trsh** [ConfettiFX/The-Forge#159]
WHY? It's just small sprites floating around? ECS mission should be to optimize speed, not drag it down. 

![Untitled7](https://user-images.githubusercontent.com/3727523/72840954-04211e00-3c9e-11ea-90fe-65fe0e2abc35.png)

gtx 750 ti 4gb, i3-6100

https://pixijs.io/bunny-mark/ > 10k sprites = 60 fps

**Comment by wolfgangfengel** [comment]
Can you send us a CPU and GPU profile so that we can check? Looks like it is CPU limited. I assume you compiled for release?

**Comment by trsh** [comment]
@wolfgangfengel no I compiled for debug. What do you mean with CPU and GPU profile?

**Comment by trsh** [comment]
A release version knocked down the CPU to ~14ms. This all is expected?

**Comment by wolfgangfengel** [comment]
It is a stress test for the CPU and memory access patterns. In debug it is expected to run slow ...
