### ISSUE TITLE
[Vulkan] Typo in error checking

### ISSUE THREAD

**Issue by jesta88** [ConfettiFX/The-Forge#16]
https://github.com/ConfettiFX/The-Forge/blob/06a43431f8f3818a86e21e4c371e2f4c81c35273/Common_3/Renderer/Vulkan/Vulkan.cpp#L802

ppBuffers should be replaced with ppTextures

**Comment by manaskulkarni786** [comment]
Technically it should work since ppBuffers / ppTextures part of a union. But you are correct - It will be better readable if the correct type is used.

**Comment by wolfgangfengel** [comment]
That should be fixed now. Can you close this issue?
