### ISSUE TITLE
13_UserInterface - Crash 

### ISSUE THREAD

**Issue by peppemas** [ConfettiFX/The-Forge#162]
Hello, 

I report a log about a crash during UserInterface example testing

[error_log.txt](https://github.com/ConfettiFX/The-Forge/files/4176514/error_log.txt)

**Comment by wolfgangfengel** [comment]
Hi,
thanks for sending this in. We will look into this.

Have a great day,
- Wolfgang

**Comment by manaskulkarni786** [comment]
Should be fixed in next release.

**Comment by wolfgangfengel** [comment]
Should be resolved with release 1.40
