### ISSUE TITLE
Support for DX12 Ultimate? (mesh shader & sampler feedback)

### ISSUE THREAD

**Issue by oscarbg** [ConfettiFX/The-Forge#174]
Hi,
just curious on plans to support new DX12 Ultimate features? it seems stable support is coming next week..
also would be nice if it can support equivalent functionality in the Vulkan backend by making use of the new Turing extensions VK_NV_mesh_shader and NV_shader_image_footprint for ex. ..
while waiting for the equivalent KHR multivendor extensions..
https://github.com/KhronosGroup/Vulkan-Ecosystem/issues/49
thanks..

PD: do you plan to migrate VK raytraing support from NV to KHR once extension is out of beta, right?

**Comment by wolfgangfengel** [comment]
Yes and yes. Shipping games based on TF has currently priority but there are lots of people at the company who really want to do this :-)

**Comment by oscarbg** [comment]
that's good news!  
thanks for answering..

**Comment by onehundredfeet** [comment]
Now that metal also has mesh shaders, will the forge support mesh shaders as a first class shader type?

**Comment by oscarbg** [comment]
don't forget there is also new Vulkan EXT mesh shader extension..

**Comment by wolfgangfengel** [comment]
I am not sure where my colleagues stand on mesh shaders. It appears like Geometry shaders and Tessellation Shaders they looked like a good idea first but now there is no consistent support or performance. Maybe we skip them ... most GPU-driven rendering now only requires a large compute shader. Why bother with Mesh Shaders?
