### ISSUE TITLE
[08_GlftViewer] Application crash on missing resource

### ISSUE THREAD

**Issue by peppemas** [ConfettiFX/The-Forge#176]
Hello, 

With unit test 08_glftViewer when you try to load the FlightHelmet model the application crash due to a missing resource file. 
It looking for FlightHelmet_basiccolor.dds instead of FlightHelmet_basiccolor.ktx

**Comment by wolfgangfengel** [comment]
thanks for bringing this up. We are looking into this!

**Comment by the-forge-sergii** [comment]
@peppemas, for the quick fix just remove '.basis' line from GltfViewer.NativeActivity\xcludedfileslist.txt file. Also make you've cleaned the solution before new build. 
We are working on proper fix now

**Comment by peppemas** [comment]
Ok thanks

**Comment by wolfgangfengel** [comment]
Should be resolved with this release.
