### ISSUE TITLE
Flickering on master when vsync is off

### ISSUE THREAD

**Issue by happydpc** [ConfettiFX/The-Forge#182]
On windows 10, turn off the vsync, it begins flicker.

![test](https://user-images.githubusercontent.com/771776/89723572-db3e5b80-da2a-11ea-8225-8db8c78f2ee0.gif)

**Comment by wolfgangfengel** [comment]
Good catch! Thanks for reporting this. We are looking into it.

**Comment by wolfgangfengel** [comment]
Can you send me your GPU chipset and driver info? This is PC right?

**Comment by happydpc** [comment]
> Can you send me your GPU chipset and driver info? Vulkan or DX12 or DX11?

GTX 2070s,  Vulkan 1.2.135

    Name: NVIDIA GeForce RTX 2070 SUPER
    Vendor id: 0x10DE
    Product id: 0x1E84
    Stepping: 161
    Driver Version: 26.21.14.4324
    Driver Date: 5-24-2020

**Comment by wolfgangfengel** [comment]
That is a good one. We test on roughly a dozen GPUs but didn't catch this one. Even now we can't reproduce so we will have to slowly see how we approach your config. Give us a few days.

**Comment by marfmotz** [comment]
> That is a good one. We test on roughly a dozen GPUs but didn't catch this one. Even now we can't reproduce so we will have to slowly see how we approach your config. Give us a few days.

Maybe this is the so-call tearing, his is too obvious, mine is small cracks in objects when rotating the camera.

**Comment by wolfgangfengel** [comment]
That should be resolved.
