### ISSUE TITLE
Use in Torque3d

### ISSUE THREAD

**Issue by SimonMGS** [ConfettiFX/The-Forge#185]
The readme mentions that The-Forge is used in Torque3D, but as far as I can tell this is not the case. I was hoping to have a look at The-Forge in the context of an accessible engine. Are there any other engines where we can make use of this renderer?

**Comment by wolfgangfengel** [comment]
I think the Torque3D developer is on the discord channel. You want to talk to him about that. Apart from Hades, which is also closed-source, there are AAA custom engines that use it but their source code is not public either.

**Comment by SimonMGS** [comment]
I saw the guy that originally proposed it was asked about it on their Discord, and his response "don't hold your breath", and that it would make more sense to build a different engine around The-Forge. As far as I can tell, there isn't a line of this project in that engine. Might be an idea to remove it from the readme, so more folks like me don't waste time discovering this for themselves.
