### ISSUE TITLE
Ubuntu: Examples fail to build

### ISSUE THREAD

**Issue by mckees** [ConfettiFX/The-Forge#186]
OS: Ubuntu 20.04
Kernel: 5.4.0-48-generic
GPU: RX 580
Vulkan Instance Version: 1.2.154
VkPhysicalDeviceDriverProperties:
---------------------------------
	driverID           = DRIVER_ID_MESA_RADV
	driverName         = radv
	driverInfo         = Mesa 20.0.8 (LLVM 10.0.0)
	conformanceVersion = 1.2.0.0

Steps:
1. Install codelite
2. git clone https://github.com/ConfettiFX/The-Forge
3. chmod +x PRE_BUILD.command && ./PRE_BUILD.command
3. Run codelite and open workspace in The-Forge/Examples_3/Unit_Tests/UbuntuCodelite
4. In the sidebar, double click on the project that you want to build to activate the project
5. Right click the project and select "build". No errors observed in build.
6. Click the little running stick person in the upper left corner of the IDE above the project list.
7. Select "Execute"

Bug:
Blank window pops up. The terminal window that pops up shows several errors because it can't find the file:
The-Forge/Examples_3/Unit_Tests/UbuntuCodelite/01_Transformations/Debug/Shaders/config.conf 

Command line output attached [here](https://github.com/ConfettiFX/The-Forge/files/5338609/TheForgeBug.txt)

**Comment by wolfgangfengel** [comment]
We are looking into this. Thanks for reporting this. I get back to you as soon as we have something.

**Comment by TheOlav0** [comment]
Hi @mckees, looking at the output it seems vulkan was not able to create the swapchain. 

Could you try to change the line in Vulkan.cpp::3389:
`swapChainCreateInfo.minImageCount = clamp(pDesc->mImageCount, caps.minImageCount, caps.maxImageCount);`
into
 `swapChainCreateInfo.minImageCount = pDesc->mImageCount;`

Then "rebuild" the project and see if you can execute it now.

**Comment by wolfgangfengel** [comment]
Should be fixed.
