### ISSUE TITLE
Multi GPU with multi monitor support?

### ISSUE THREAD

**Issue by TLaviron** [ConfettiFX/The-Forge#187]
Is it possible to use The Forge with multiple unlinked GPUs?
If I understand correctly there is support for linked multi GPU (i.e. SLI/CrossFire), but as far as I know this only allows a single monitor.
A typical use case would be having two GPUs with a monitor each, where each GPU executes commands for rendering content on its attached display.

Is this currently possible or planned as a future feature?

**Comment by wolfgangfengel** [comment]
TF is used mostly for games and now also business applications, we do not have any plan to support two GPUs with a monitor each at the moment. In case you want to implement that we can invite you to our internal repository.

**Comment by TLaviron** [comment]
We're in the process of transitioning our D3D11-based application to a Vulkan backend, using TF.
This is not top priority since we have to get everything else working correctly in a single GPU/single window context first, but we will need it at some point so we are going to implement support for multi GPU anyway.
If we can contribute it back upstream, all the better. We are planning to support D3D12 later as well, so we could provide an implementation for both backends.

**Comment by wolfgangfengel** [comment]
@TLaviron if you could follow up via private e-mail. I would make sure you would be added to our internal repository so that you can check out the latest development.

**Comment by wolfgangfengel** [comment]
Hi @TLaviron , can I close this issue?
