### ISSUE TITLE
typo - lowercase L in first DepthStencilClearFlags constant "ClEAR_DEPTH"

### ISSUE THREAD

**Issue by kevinw** [ConfettiFX/The-Forge#188]
https://github.com/ConfettiFX/The-Forge/blob/55efcee5ce8349b0a7ec5db87968b3fd4ccbb660/Common_3/Renderer/IRenderer.h#L569

**Comment by wolfgangfengel** [comment]
Nice catch :-)

**Comment by wolfgangfengel** [comment]
Should be fixed.
