### ISSUE TITLE
The-Forge 1.47 Can't build by Xcode 12.3 on macOS 11.1

### ISSUE THREAD

**Issue by ldbfrank** [ConfettiFX/The-Forge#191]
I have tried to build 1.47 by Xcode 12.3 on macOS 11.1, but there are many errors in ozz_base, please check the image uploaded. Thanks.
![2020-12-27 04 17 32](https://user-images.githubusercontent.com/758540/103158816-3798f080-47fd-11eb-8be8-42b92893f9fb.png)

**Comment by ldbfrank** [comment]
Attachment is the build error log.
[Build target ozz_base_2020-12-27T04-31-08.txt](https://github.com/ConfettiFX/The-Forge/files/5743608/Build.target.ozz_base_2020-12-27T04-31-08.txt)

**Comment by wolfgangfengel** [comment]
Thanks for the bug report. At this moment we don't support this XCode version and macOS version. You can find the versions we support on the main GitHub page. Those are the ones we are testing.
