### ISSUE TITLE
The-Forge headers polluting includers with Obj-C code

### ISSUE THREAD

**Issue by Takarashy-URender** [ConfettiFX/The-Forge#193]
Hello,
we have an issue with The-Forge headers pulling Obj-C code with them on MacOS. This has the consequence that every class/header that includes The-Forge headers on Mac, has to be compiled with Obj-C++ and cannot be compiled with plain old good C++. This might be a small issue for applications running exclusively on Mac (all in Obj-C / Swift), but for cross-platform development, it makes things more complicated since we have to check each file and set it either to C++ or Obj-C++ based on the includes.

Is this intended, that on Mac, all code including The-Forge headers should be compiled with Obj-C++?

All the best and thanks a lot for the great work The-Forge team is doing 😍

**Comment by Takarashy-URender** [comment]
Would it be by any chance an option for you that we create a pull request addressing this issue?

**Comment by wolfgangfengel** [comment]
@Takarashy-URender can you please send me your skype id and we will invite you to join our internal GitLab repository for this. We can discuss it there.

**Comment by Takarashy-URender** [comment]
That would be great thank you 👍 I have sent you my skype id over discord.

**Comment by Takarashy-URender** [comment]
Hi, any news regarding this issue? Did you find my skype-id and invite on discord, or should I post my skype-id over another channel?

**Comment by wolfgangfengel** [comment]
I am closing this. We discussed it but for us, this doesn't make sense. We recommended that they implement this in their cut-of-the-code base.
