### ISSUE TITLE
[Vulkan] Wrong value passed to depthClampEnable

### ISSUE THREAD

**Issue by jesta88** [ConfettiFX/The-Forge#20]
https://github.com/ConfettiFX/The-Forge/blob/38b445c5d7dfd885a981ab2a42eab4517e030207/Common_3/Renderer/Vulkan/Vulkan.cpp#L2919

Should be rs.depthClampEnable = pRasterizerState->DepthClampEnable;

**Comment by wolfgangfengel** [comment]
That should be fixed now. Can you close this issue?
