### ISSUE TITLE
Compile time error with conflict between '#define delete' and C++11 Mutex copy-constructor deletion ('= delete;')

### ISSUE THREAD

**Issue by vlmillet** [ConfettiFX/The-Forge#210]
There is a strange `#define delete` in `IMemory.h` which, when included before `IThread.h` enters in collision with `MutexLock(const MutexLock& rhs) = delete;` (C++11). Redefining `delete` is something that should be avoided IMHO to avoid this kind of difficult-to-track compilation failures : VS studio does not get you to the original `#define` and just prompt a `static_assert`.

**Comment by manas-kulkarni** [comment]
Yes. It is to discourage using the C/C++ memory allocation/deallocation functions directly and instead use the tf_ variants. If you notice, IMemory.h is always included last in all source files. That should fix the error. If for some reason you are forced to include IMemory.h in a header file, there is a macro you can set - IMEMORY_FROM_HEADER

**Comment by wolfgangfengel** [comment]
Usage as intended ...
