### ISSUE TITLE
Failed to compile some projects, such as "28_Skinning" on vs2019

### ISSUE THREAD

**Issue by qy-wang** [ConfettiFX/The-Forge#214]
C function `tolower()`: identifier not found.
`#include <ctype.h>` in basisu.h could resolve.
Since it is third party, I am not sure whether new lib would solve this issue.

**Comment by wolfgangfengel** [comment]
We only support Visual Studio 2017. Please check out what is supported on the Github main page.

**Comment by qy-wang** [comment]
Thanks, seems I can't give up vs2017.
By the way, on vs2019, it works well except for this.
