### ISSUE TITLE
[FileSystem] Typo in ZipOpen

### ISSUE THREAD

**Issue by maihd** [ConfettiFX/The-Forge#215]
https://github.com/ConfettiFX/The-Forge/blob/4aa015991bcf383d9f83d94e4e2a74fd152dbcad/Common_3/OS/FileSystem/ZipFileSystem.cpp#L43
The returned value should be `false` instead of `NULL`

**Comment by wolfgangfengel** [comment]
Thank for bringing this up ... we will fix this in the next release.
