### ISSUE TITLE
Vk/Stencil test reference value not exposed

### ISSUE THREAD

**Issue by gjaegy** [ConfettiFX/The-Forge#217]
Hi, 

It seems TheForge doesn't expose the stencil test reference value in it's public interface. Is there any reason for that ?

For instance, util_to_depth_desc() (in vulkan.cpp) set both front and back reference to 0... I'm going to add it, however, I thought I would ask first, as stencil test is still a commonly used feature. Have I missed any point ?

Cheers,
Gregory Jaegy

**Comment by manas-kulkarni** [comment]
Shouldn't cmdSetStencilReferenceValue cover this for you?

**Comment by gjaegy** [comment]
Hi, you are right, this will work. Thanks for that.

It seems the version of TheForge we are using is a bit older and doesn't contain this additon. I've been able to easily patch it here, temporarly, adding a member in the DepthStateDesc structure and passing it down to the VkPipelineDepthStencilStateCreateInfo structure in Vulkan.cpp/util_to_depth_desc(). 

Actually the static way (i.e. the patch I've done) works well for us, out of curiosity, is there any specific reason to use a dynamic state instead ? I'll use cmdSetStencilReferenceValue() in the future once we decide to update (I guess there is no significant performance penalty, isn't it?).

**Comment by manas-kulkarni** [comment]
The only reason is different stencil reference values mean more pipelines as stencil reference will be baked into the pipeline state. Using a dynamic state for stencil reference makes it more flexible. We haven't seen any performance problems

**Comment by wolfgangfengel** [comment]
Can we close it?

**Comment by gjaegy** [comment]
Yes we can, thanks!


________________________________
