### ISSUE TITLE
Question : way to support Vulkan SpecializationInfo?

### ISSUE THREAD

**Issue by Michael-Lfx** [ConfettiFX/The-Forge#219]
https://github.com/ConfettiFX/The-Forge/blob/076aa5dcd8fd71cc83905431c92360183c7027d9/Common_3/Renderer/Vulkan/Vulkan.cpp#L5913

**Comment by manas-kulkarni** [comment]
Yes. We are missing support for this useful feature. Would only apply to VK and Metal. Making a note of it. We will have it in the next release

**Comment by wolfgangfengel** [comment]
Should be available in Release 1.50
