### ISSUE TITLE
Question: MTLFeatureSet_macOS_GPUFamily2_v1 and macOS 10.14

### ISSUE THREAD

**Issue by Michael-Lfx** [ConfettiFX/The-Forge#222]
https://github.com/ConfettiFX/The-Forge/blob/076aa5dcd8fd71cc83905431c92360183c7027d9/Common_3/Renderer/Metal/MetalRenderer.mm#L1795-L1798

  Based on Apple document that `MTLFeatureSet_macOS_GPUFamily2_v1` requires macOS 10.14 and last version is also `if (@available(macOS 10.14, *)) `. Why should we update to macOS 10.15? `newBufferWithLength:options:offset:` requires  macOS 10.15?

**Comment by manas-kulkarni** [comment]
https://developer.apple.com/documentation/metal/mtlheap/3152522-newbufferwithlength
Manual heap placement requires macOS 10.15+, iOS 13.0+

**Comment by Michael-Lfx** [comment]
Thank you!
