### ISSUE TITLE
Request: Support V-Sync off on Metal unit tests..

### ISSUE THREAD

**Issue by oscarbg** [ConfettiFX/The-Forge#23]
Hi,
would be nice if support for disabling Vsync on Metal could be added.. I think that this may require MacOS 10.13 and/or Metal 2 features but could be good to see Compute and ExecuteIndirect samples make use of full GPU load..
also adding support for others backends: Vulkan and D3D12 would be nice..

**Comment by wolfgangfengel** [comment]
You can toggle now V-Sync ... let us know how it goes for you.
