### ISSUE TITLE
Request: Support Xcode Quick Look Debugging 

### ISSUE THREAD

**Issue by Michael-Lfx** [ConfettiFX/The-Forge#232]
It's convenient for multimedia developers to view the content of texture using Xcode Quick Look Debugging without capturing the whole gpu frame which can spend a few seconds for replaying a complex frame.

Maybe the following code is acceptable for a temp debug session.

```objc
TextureLoadDesc textureDesc = {};
textureDesc.pFileName = "QuickLookTest";
textureDesc.ppTexture = &pDebugTexture;
textureDesc.mContainer = TEXTURE_CONTAINER_JPG;
addResource(&textureDesc, NULL);
// ...
waitForAllResourceLoads();

TextureXcodeQuickLook* quickLook = [[TextureXcodeQuickLook alloc] initWithTexture:pDebugTexture];
printf("%p\n", quickLook); //meaningless, just for avoiding compile warning
```

It looks like the following debug screen capture of demo 01_Transformations.
<img width="2560" alt="截屏2021-10-29 下午7 13 35" src="https://user-images.githubusercontent.com/9588926/139425936-36a80fe6-ca78-4a7b-878d-2e3f05f52842.png">

**Comment by wolfgangfengel** [comment]
Sorry TF is mostly for game developers. It wouldn't be a good idea to add something on the App code for XCode.
