### ISSUE TITLE
Camera ghosting in all samples

### ISSUE THREAD

**Issue by oferrun** [ConfettiFX/The-Forge#233]
Hey,
I started playing with the forge and it looks really promising.
I have one issue that comes up across all unit tests though.
Whenever I move the camera with the keyboard I get significant ghosting of the rendered objects.
This is especially visible in the Skinning Unit test where the soldier has grey hallow whenever the camera is moved. (Also happens on all other unit tests as well).
Any suggestions to what is going on?
I am running on Windows with the latest source code from github.
P.S. tried enabling vsync but did not have any effect

Thanks!

**Comment by wolfgangfengel** [comment]
What GPU and driver are you running on? Maybe we have it in the office and can replicate the scenario.

**Comment by oferrun** [comment]
AMD FirePro W7100
Radeon Pro Software Version
21.Q2.1 - which is the latest driver
I am supplying a video showing the ghosting.

https://user-images.githubusercontent.com/13603430/140412137-e70fd903-051c-4ca2-8c77-e059622f653e.mp4

**Comment by oferrun** [comment]
Hey, it seems the problem is with my screen and not with the forge.
Sorry about that ... :(
