### ISSUE TITLE
Shader reflection is incomplete

### ISSUE THREAD

**Issue by vlmillet** [ConfettiFX/The-Forge#234]
On the description of the main project page, it is said that cross platform _Shader Reflection_ is available, but digging into it I'm **unable to find the Data Type / Struct Members reflection anywhere** (like SPIRV does for example). 
`ShaderReflection` class only seems to give resource kind and size but not data type reflection which is mandatory to use it for generic binding purposes. 

Moreover, **vertex input reflection does not include vertex attribute location** which is necessary to fill up the `VertexAttrib` struct passed to the `addPipeline` function (maybe there is another way to get this location somewhere from the name ?)

I'm porting my Vulkan engine to TheForge and I am unable to have SPIRV reflection equivalent to expose shader uniform UI, auto bind vertex attribute or make debug type-checks as I did before.

Have I missed something anywhere ? 

If not I can help contribute to add it to TheForge if you want, at least for the Vulkan API as a first step because I mostly know this API (other APIs could fallback to empty data type reflection while waiting for them to be implemented).

**Comment by manas-kulkarni** [comment]
Thanks for reporting the issue. It is possible, we missed some of the variable reflection. Would you be interested in joining our internal repository where we develop the framework and add the missing reflection data?

**Comment by vlmillet** [comment]
Yes of course !

**Comment by wolfgangfengel** [comment]
Can you please send me your e-mail. I suggest you use Discord and a private chat ...

**Comment by vlmillet** [comment]
I sent you an email through the The-Forge contact section.

**Comment by wolfgangfengel** [comment]
Should be resolved?
