### ISSUE TITLE
Support Vulkan multiple Subpasses and InputAttachments

### ISSUE THREAD

**Issue by Michael-Lfx** [ConfettiFX/The-Forge#238]
https://github.com/ConfettiFX/The-Forge/blob/e882fbc000b2915b52c98fe3a8c791930490dd3c/Common_3/Renderer/Vulkan/Vulkan.cpp#L730

**Comment by manas-kulkarni** [comment]
This is on the radar but will take time to implement subpasses correctly to work with all other APIs

**Comment by wolfgangfengel** [comment]
To get back to this:: now that the VK_KHR_dynamic_rendering is released we are hoping that sub passes are moved back into the device driver space where they make more sense to me. We are hoping that everyone (hardware vendors and device driver writers) picks up that extension as fast as possible.
