### ISSUE TITLE
Request: don't require "iOS GPU family 4" unless explicitily needed..

### ISSUE THREAD

**Issue by oscarbg** [ConfettiFX/The-Forge#24]
Hi,
nice to see now all units tests came with IOS support.. but seems I compiled 01 unit test and doesn't run
on ipad Pro 10.5 (iOS GPU family 3) because says texture cube map arrays need ios gpu family 4..
this is only supported on latest iphones and iphone x..
don't know if engine could lower requiriments to "ios gpu family 3" with much more use base..
for example 07 tesselation unit test should run on family 3 devices..
thanks..

**Comment by wolfgangfengel** [comment]
We do not support iOS in the moment :-) but we are building up a build system to test various iOS devices. As soon as we have some confidence that it runs on a wider range of devices, we will ship the iOS support. Give us a bit more time ... it will be in the news section of the website, when it happens.

**Comment by amsgames94** [comment]
We're targetting iOS_GPUFamily3_v3 with our latest iOS release, so this should no longer be an issue :)
