### ISSUE TITLE
found visible lag may caused by queuePresent

### ISSUE THREAD

**Issue by yaoyao-cn** [ConfettiFX/The-Forge#240]
Have you encountered this phenomenon ? i strugged to find the reason for several days, but failed
Indead, i am not sure whether it is caused by queuePresent
I use the VK_PRESENT_MODE_MAILBOX_KHR mode

thank you very much !

# 16_Raytracing demo:
![tf_lag](https://user-images.githubusercontent.com/10138823/145946853-96e0a3ef-434e-4228-8c87-508abd539549.gif)

# my program (fps:20):
![my_lag](https://user-images.githubusercontent.com/10138823/145947004-d6879ecf-2ac5-408d-926a-97f42ff4b067.gif)

**Comment by wolfgangfengel** [comment]
You are looking at a Path Tracer ... this program updates like this.
