### ISSUE TITLE
Support for new Metal Ray Tracing features?

### ISSUE THREAD

**Issue by unphased** [ConfettiFX/The-Forge#248]
https://developer.apple.com/videos/play/wwdc2021/10150/

I'm very impressed by this software and I'm looking forward to experimenting with it soon. The wide platform support is particularly noteworthy. I'd like to know what the author's impression of how far forward the recent Metal features combined with recent M1 Max GPU can push the state of ray tracing on macOS. 

I've been looking around, though not so extensively yet, but it does not seem like MoltenVK is close yet to supporting ray tracing. Well a man can dream...

**Comment by wolfgangfengel** [comment]
We support metal Ray Tracing in the ray tracing example ...

**Comment by unphased** [comment]
Thanks, i was not sure if the the linked API features (toward end of the video) that have the improved efficiency are implemented or not but I will take a look!

**Comment by wolfgangfengel** [comment]
I think we can close this now?
