### ISSUE TITLE
Windows 7 problems

### ISSUE THREAD

**Issue by quetzalsly** [ConfettiFX/The-Forge#249]
* GetDpiForSystem() not supported on win7, causes dll error upon running
* System cant find a bunch of dll's including d3d12.dll
* When commenting out all d3d and only leaving vulkan, the sample runs but instantly crashes when trying to load skybox.vert
* When running on debug x64 it crashes somewhere in device creation

The readme says windows 7 is supported but it seems its not?

Edit: after messing around for a while I randomly moved all the files from Shaders/VULKAN to just Shaders/ and it worked. I just dont understand how this was meant to be working? weird.

**Comment by wolfgangfengel** [comment]
Thanks for bringing this up ... as I said in Discord we are happy to invite you to help us provide a fix. We don't have a Win 7 machine anymore ...

**Comment by wolfgangfengel** [comment]
We are looking into this from a different angle. So it is in our internal issue list ... I am hoping to have a fix in the next release.

**Comment by wolfgangfengel** [comment]
Should be resolved.
