### ISSUE TITLE
[Windows7:Vulkan] Problem in FpsCameraController::onMouseMove() and slow/stopped rendering

### ISSUE THREAD

**Issue by madwax** [ConfettiFX/The-Forge#25]
I know my setup might not be supported but I've seen what might be a Windows7/10 difference and so this is more of a FYI as it does not effect the core of The-Forge.

1) Setup Windows7/M$VS15/ Dual monitor (3440x1440|1920x1200)
2) I've changed all the project files to use VULKAN and not DIRECTX12. Also not using the Windows 10 SDK but 8.1.  
3) Run 01_Transformations -> runs on the bigger screen.
4) move mouse over the window.
5) click and it stops rendering.  Planets just stop.

Chased the problem down to FpsCameraController::onMouseMove() and the call to setMousePositionRelative().  The setMousePositionRelative() calls the Win32 SetCursorPos(), Windows post's a WM_MOUSEMOVE which in turn ends up calling FpsCameraController::onMouseMove().

If I comment out setMousePositionRelative() it works just the same as my OSX/Mac Pro

**Comment by manaskulkarni786** [comment]
This is related to the SDKs before Windows Fall Creators update. Expect a fix soon.
