### ISSUE TITLE
Toggle for 'setupAPISwitchingUI' in WindowsBase.cpp

### ISSUE THREAD

**Issue by swan-gh** [ConfettiFX/The-Forge#252]
Hello,

Generally when I use an engine I try not to edit the engine source at all, to make it as seamless as possible when updating to newer versions. So relating to `WindowsMain` and the `DEFINE_APPLICATION_MAIN` macro, are these intended for production use? And if so, then how is the developer expected to toggle or get rid of the API Switching UI Component without editing the engine source?

At the moment I want to use `WindowsMain` and `DEFINE_APPLICATION_MAIN` for production but I cannot remove the API Switching UI Component without editing the source directly, because the variables are static and there is no external-facing settings to toggle it.

Many thanks,
Swan

**Comment by manas-kulkarni** [comment]
Good point. Will make it customizable in next release

**Comment by wolfgangfengel** [comment]
Should be resolved.
