### ISSUE TITLE
Visibility Buffer on iOS

### ISSUE THREAD

**Issue by zyjisdog** [ConfettiFX/The-Forge#253]
The visibility buffer demo seems to work on iPhone 12 (A14, MTLGPUFamilyApple7, max number of the texture argument buffe is 128), and I saw a folder named 'Visibility_Buffer_iOS' in the visibility buffer project, but there is no iOS target in the xcode project.
I tried to port the macOS target to iOS by duplicate and modify it but it did't work.

**Comment by wolfgangfengel** [comment]
We are working on this. It won't make it to the next release but maybe the one after.

**Comment by zyjisdog** [comment]
In addition, A14 delivered features including primitive ID and barycentric coordinates, which may help you to refactor the iOS version of visibility buffer.
Ref: https://developer.apple.com/videos/play/tech-talks/10858/

**Comment by wolfgangfengel** [comment]
This should work now. Have you tried? You need a decent phone ...
