### ISSUE TITLE
(Windows 7) WindowsThread.c - SetThreadDescription()

### ISSUE THREAD

**Issue by haloman30** [ConfettiFX/The-Forge#255]
Hello! I've been looking around to toy with several graphics libraries for a game engine I'm in the process of building, and I ran into a minor hiccup with this one.

I'm not sure if you guys still support Windows 7 at all, but I just did a fresh clone and build attempt and I ran into a bit of an issue - When compiling OS, it fails in `WindowsThread.c` at a function called `SetThreadDescription`. After some research, it seems that this function doesn't exist at all under Windows 7 (or 8 for that matter) as detailed [here](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreaddescription).

Commenting out these two lines results in compilation (seemingly) without issue, though I have to imagine that randomly commenting out lines won't be ideal long-term.

`Common_3\OS\Windows\WindowsThread.c:`
```cpp
/*137*/                HRESULT res = SetThreadDescription(GetCurrentThread(), windowsThreadName);
/*138*/                ASSERT(!FAILED(res));
```

The error log is as follows:
```
1>I:\Development\Github\ConfettiFX\The-Forge\Common_3\OS\Windows\WindowsThread.c(137,37): error C2220: the following warning is treated as an error
1>I:\Development\Github\ConfettiFX\The-Forge\Common_3\OS\Windows\WindowsThread.c(137,37): warning C4013: 'SetThreadDescription' undefined; assuming extern returning int
```

Would be really cool to see this fixed - as outside of commenting out D3D12 rendering support, this was the only roadblock to getting it to compile and run under Win7.

**Comment by wolfgangfengel** [comment]
What kind of Windows 7 setup do you have? Which Windows SDK are you using? I realize I forgot to put that info on the GitHub page. We probably need a define around this for specific Windows SDK version because when we tested this it worked :-)

**Comment by haloman30** [comment]
Was using the 8.1 SDK as its a lot easier to obtain than the Win7 SDK

**Comment by wolfgangfengel** [comment]
I believe we used the same one ... I double-check and get back to you.

**Comment by wolfgangfengel** [comment]
Ok. Turns out we are using the windows 10 SDK in "windows 7 mode" for testing. Let me know if this is a problem.

**Comment by haloman30** [comment]
If I have it targeted to 10.0 SDK, it compiles but then no longer runs:
![image](https://user-images.githubusercontent.com/7994024/169437332-260661ee-d0f8-48e1-a63d-8541bda16b78.png)

I'm not familiar with this "Windows 7 Mode" feature of the SDK, so I'm not sure if theres some additional step I need to perform.

**Comment by wolfgangfengel** [comment]
Ok. I make a note of this and we are going to look into it. I assume this will might end in two ways: either we describe how we installed windows 10 SDK and enabled "Windows 7 Mode" here on Github or we see if we can put a suitable define around this code with Windows 8.1 SDK. I don't know what the better way is at the moment.
Thanks again for bringing this up!

**Comment by manas-kulkarni** [comment]
Fixed with the latest release

**Comment by KosKos9052** [comment]
It showed for me the Same problem with Unity Games, my PC is not powerful enough to run latest windows version so.
