### ISSUE TITLE
No logging on macOS

### ISSUE THREAD

**Issue by grakkpl** [ConfettiFX/The-Forge#26]
Is there any chance you could fix logging on macOS? Is there any other way of getting the performance score (some avg fps)?

https://github.com/ConfettiFX/The-Forge/blob/ed732fce53678eb5949465f44eeadef44025360f/Common_3/OS/Logging/LogManager.cpp#L60

**Comment by grakkpl** [comment]
It also depends on #23 - without vsync off support (almost) all workloads are capped on ~16ms, even on low-end Mac

**Comment by AntoineConffx** [comment]
Closing this as logging has been enabled for both macOS and iOS in the latest Pull request:  #43
