### ISSUE TITLE
Will Metal 3 be supported?

### ISSUE THREAD

**Issue by NewSkyLineTwitter** [ConfettiFX/The-Forge#265]
When Metal 3 releases, so probably with macOS 13 and iPadOS 16, October 24, will it get support for it? Metal 3 has some awesome features like MetalFX, Mesh shaders and Offline shader compilation. Metal 3 is a game changer for gaming on Mac, so I hope The Forge will support it. 😃

**Comment by wolfgangfengel** [comment]
If you watched the last Apple keynote. They have shown the game No Man's Sky running on MacOS ... this game uses The Forge and it uses Metal 3.

**Comment by NewSkyLineTwitter** [comment]
Alright thanks

**Comment by oscarbg** [comment]
Any news on this?

**Comment by JonahGoldsmith** [comment]
They have been supporting Metal 3 for quite a while...
