### ISSUE TITLE
Is there a demo that can be downloaded?

### ISSUE THREAD

**Issue by lonnietc** [ConfettiFX/The-Forge#266]
Hello,

I came across the-forge and would like to download a demo of it if possible.

Thanks

**Comment by wolfgangfengel** [comment]
We don't have a demo. We have a lot of functional tests that show you various features. It is not a game engine. It is a rendering framework. So it is meant for people who -for example- want to upgrade their 10 year old game to run on modern platforms or to build a game engine from scratch.

**Comment by lonnietc** [comment]
Actually, that type of thing is what I may be seeking as I have been working with an older game engine "Tesseract" (~2015) and was thinking about how it might be upgraded to a new framework. 

I had considered possibly doing something like this with O3DE and integrate it into Tesseract but then found your site.

**Comment by wolfgangfengel** [comment]
When you scroll down on the main GitHub page you can find a list of games using it. I think the two things missing from this list are Google Stadia and the Facebook Application framework. Both of those are using it too. 
No Man's Sky is using The Forge now too ... it is used in games. The games that use it are our best demos :-)
