### ISSUE TITLE
has any plans to support SV_Coverage (or gl_SampleMaskIn in glsl) Semantic in FSL ?

### ISSUE THREAD

**Issue by yaoyao-cn** [ConfettiFX/The-Forge#267]
I use SV_Coverage  to optimize the MSAA resolve pass, now I use it like this:

```glsl
#ifdef RENDERER_API_D3D12
	Out.pm = In.coverage;
#else
	Out.pm = gl_SampleMaskIn[0] ;
#endif
```

which is not very convenient

**Comment by wolfgangfengel** [comment]
Thanks for submitting this. I add an issue to our internal issue list for this.

**Comment by wolfgangfengel** [comment]
I think this is in the next release.

**Comment by manas-kulkarni** [comment]
Fixed with latest release
