### ISSUE TITLE
Unable to build with Visual Studio 2022

### ISSUE THREAD

**Issue by OttoHatt** [ConfettiFX/The-Forge#268]
This project won't build in Visual Studio 2022. The bundled version of the `EASTL` is outdated and references some removed constants, swapping the `numeric_limits.h` file out for [a newer version](https://github.com/electronicarts/EASTL/blob/master/include/EASTL/numeric_limits.h) allows you to build.

Very minor, and I imagine this has already been fixed internally!

**Comment by wolfgangfengel** [comment]
We only support Visual Studio 2017. We try to stay backward compatible to help game developers build games. Every Visual Studio version has its own problems. It reduces productivity to support more than one.
