### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by mxplusb** [ConfettiFX/The-Forge#269]
Would y'all be able to tag the recent releases to make them easier to work with? The most recent release is 1.53 but the most recent tag is 1.50.

**Comment by wolfgangfengel** [comment]
Working on it :-) Thanks for bringing this up ..

**Comment by oscarbg** [comment]
+1

**Comment by oscarbg** [comment]
Unrelated, but plan on continue making some new releases.. new is 8-9 months old..
Presumably incoporating some Metal improvements from “No Man Sky” port?
Thanks..

**Comment by wolfgangfengel** [comment]
Should be fixed now?
