### ISSUE TITLE
Rendering artifacts when disabling HDAO option in Visibility Buffer example on Windows PC with DirectX12 and Vulkan backend in The Forge 1.53

### ISSUE THREAD

**Issue by logic-three-body** [ConfettiFX/The-Forge#280]
## [Rendering Issue]: HDAO option causes previous frame's rendering result to remain

When running the Visibility Buffer example on Windows PC with DirectX12 and Vulkan, I noticed that there is residual rendering information from the previous frame after turning off the HDAO option. This issue occurs on The Forge version 1.53, but not on version 1.50.

### Issue Details

- Example name: Visibility Buffer
- Option name: HDAO
- Expected result: When turning off the HDAO option in the Visibility Buffer example, there should be no residual rendering information from the previous frame.
- Actual result: Residual rendering information from the previous frame is present after turning off the HDAO option in the Visibility Buffer example.

### Version Information

- The Forge version: 1.53
- Previous working version: 1.50

### Running Environment

- OS:  PC Windows10
- Graphics API: DirectX12 and Vulkan
- The Forge version: 1.53 (issue occurs), 1.50 (issue not present)

![image](https://user-images.githubusercontent.com/67043073/225239683-7973857d-c3f3-48f7-b447-f974f22e6b1e.png)
![image](https://user-images.githubusercontent.com/67043073/225239995-8008299b-c90f-405a-8ef9-f8d0ca699aa6.png)

**Comment by wolfgangfengel** [comment]
Thanks for being so diligent. I think we covered that already ... now just have to ship the new release.
