### ISSUE TITLE
Materials playground hair assets missing

### ISSUE THREAD

**Issue by panthuncia** [ConfettiFX/The-Forge#284]
The resource files required to run the materials playground TressFX implementation appear to be missing. The unit test crashes on startup.

Any chance these could be added?

Thanks!

**Comment by wolfgangfengel** [comment]
Did you not find it in the art assets? Should be in the folder Art. Art gets created after you run the batch file ...

**Comment by panthuncia** [comment]
Whoops, I didn't run the bat file. Sorry!
