### ISSUE TITLE
Audio?

### ISSUE THREAD

**Issue by mdsitton** [ConfettiFX/The-Forge#287]
The website for The forge has a reference to a cross platform audio system but i don't see anything for that in the repo what is the deal with that?
https://theforge.dev/products/the-forge/

**Comment by MasterDrake** [comment]
Can't say for sure but maybe they meant SoLoud, it was in a couple of commits/releases but they removed it because their target audience will either use FMOD or Wwise anyway

**Comment by wolfgangfengel** [comment]
We had SoLoud integrated for a while but the integration was never cross-platform. It dangled around for months in this state and unfortunately, we even shipped it without proper integration. So we removed it again until someone in the team finds the time to make a proper integration.
