### ISSUE TITLE
Problem in ImageFormat::GetBytesPerPixel()

### ISSUE THREAD

**Issue by madwax** [ConfettiFX/The-Forge#29]
I noticed a lot of ASSERT(format <= ImageFormat::D32F) messages while running Visibility_Buffer (and I think some of the other examples?) so I had a look.

The problem is format == ImageFormat::BGRA8 which is < ImageFormat::D32F so the return value is junk as it's out of range of bytesPP[]

I've done a if(format == ImageFormat::BGRA8) { return 4; } but should proper range checking be done?

**Comment by wolfgangfengel** [comment]
Should be solved with the release today.
