### ISSUE TITLE
Issue of fullscreen windows at start

### ISSUE THREAD

**Issue by ilyachastikov** [ConfettiFX/The-Forge#290]
If fullscreen is needed at start and if creating constructor for this for example: 
```
Transformations() {
	mSettings.mFullScreen = true;
	mSettings.mMonitorIndex = 0;
}
```
then the application will fail because `pWindowAppRef->pWindow` is not set before `toggleFullscreen(winDesc)` in file WindowsWindow.cpp. I think that the best solution to fix this issue is adding string `pWindowAppRef->pWindow = winDesc;` after 550 string number in WindowsWindow.cpp. Also I think that to adjust initial parameters in constructor is not flexible because memory allocator and filesystem is not set for moment of constructor invocation. It will be good to add some additional virtual function for this for initialization some parameters before creating window but after memory allocator and filesystem initialization.

**Comment by manas-kulkarni** [comment]
Is this fixed with latest release? Not able to repro failure with fullscreen set to true in constructor.
Function before Init but after base systems initialized is a good idea. It will be in the next release
