### ISSUE TITLE
Python regex warnings

### ISSUE THREAD

**Issue by helviett** [ConfettiFX/The-Forge#298]
You have to either escape string properly or use regex string literal (prepend string literal with **r**). Here is patch:
[regex_fix.patch](https://github.com/ConfettiFX/The-Forge/files/14155830/regex_fix.patch)

**Comment by wolfgangfengel** [comment]
I hope this problem is fixed with the latest release. Can you confirm?

**Comment by helviett** [comment]
Yes, no more warnings.
