### ISSUE TITLE
Tried to launch different examples, nothing works, got different errors

### ISSUE THREAD

**Issue by pyskonus** [ConfettiFX/The-Forge#313]
My device is a Mac mini with M2 chip.
Before I describe the errors, I'd like to say that I don't know what to build so I tried building different things in Examples_3 folder.

Issues with `The-Forge/Examples_3/Unit_Tests/macOS Xcode/16_Raytracing/16_Raytracing.xcodeproj`:

Immediately after launch, an assert stops the execution.
In `The-Forge/Examples_3/Unit_Tests/src/16_Raytracing/16_Raytracing.cpp` on lines 213 and 214 there is this code:
`font.pFontPath = "TitilliumText/TitilliumText-Bold.otf";`
`fntDefineFonts(&font, 1, &gFontID);`
in `fntDefineFonts` on line 630 the assert stops the program because on line 610 `fsOpenStreamFromPath(RD_FONTS, pDescs[i].pFontPath, FM_READ, &fh)` returns false.

The same error occurred when running `09_LightShadowPlayground.xcodeproj`.
So I assume the program cannot find file `TitilliumText-Bold.otf`.
There is indeed no such file in the freshly cloned project or anywhere else in my filesystem.

I also encountered an issue when building `Visibility_Buffer.xcodeproj`. Build failed, and this was listed among errors in Xcode:
`Command PhaseScriptExecution failed with a nonzero exit code`

**Comment by AntoineConffx** [comment]
Did you run PRE_BUILD.command ? do you have the Art folder in the root of the repo ? 
I've just tried on a clean repo and it seems to work just fine.

**Comment by pyskonus** [comment]
Running PRE_BUILD.command helped. I was so distracted I didn't even notice this file in the project. Thank you for your time.
