### ISSUE TITLE
[Shader Debug] Enable debugging on shaders - vulkan GL_EXT_debug_printf

### ISSUE THREAD

**Issue by Hideman85** [ConfettiFX/The-Forge#315]
I would like to enable shader debugging to help me find issues in my implementation.
Right now I'm using Vulkan backend only and so I would like to have `printf` with `#extension GL_EXT_debug_printf : enable` but no way to have this working.
As soon as I put a string in my shader, I'm getting the compilation error
```
ERROR :  'string literal' : required extension not requested: Possible extensions include:
GL_EXT_debug_printf
GL_EXT_spirv_intrinsics
```
And when I put `#extension GL_EXT_debug_printf : enable` I'm getting
```
error: invalid preprocessing directive #extension
    1 | #extension GL_EXT_debug_printf : enable
```
I checked the `fsl.py` compiler and seem no options for enabling this. How can I do so?

**Comment by david-tf** [comment]
This does not work because fsl runs its own preprocessor step, you can use this:

    @fsl_extension GL_EXT_debug_printf: enable

    float4 PS_MAIN(VSOutput In)
    {
        INIT_MAIN;
        float4 Out;
        debugPrintfEXT("Hello World!");

**Comment by david-tf** [comment]
You will need to add VK_KHR_SHADER_NON_SEMANTIC_INFO_EXTENSION_NAME to the ppDeviceExtensions/mDeviceExtensionCount RendererDesc.
