### ISSUE TITLE
Missing PathStatement.SteamOS.txt after running PRE_BUILD.command

### ISSUE THREAD

**Issue by Klaus-E-J** [ConfettiFX/The-Forge#317]
After conning the repository, running PRE_BUILD.command and building the 01_Transformations workspace, I encountered an error during the post-build commands. The error occurred while executing the following instruction from the Codelite project:

`rsync -u $(WorkspacePath)/../../../Art/PathStatement.SteamOS.txt $(ProjectPath)/$(ConfigurationName)/PathStatement.txt`

Here is the error message:

`rsync: [sender] link_stat "/home/[user]/The-Forge/The-Forge-2/Art/PathStatement.SteamOS.txt" failed: No such file or directory (2)`

I tried running PRE_BUILD.command again, but the issue persists.

Additionally, I noticed that `PathStatement.SteamOS.txt` is mentioned in several unit tests.
Should this file be added in `Art.zip`?

I also want to mention that when I run the unit tests, I encounter a few runtime errors related to missing files, even though they were downloaded.

**Comment by AntoineConffx** [comment]
We just updated the Art.zip that PRE_BUILD grabs. That should fix it.

**Comment by Klaus-E-J** [comment]
Thanks. That fixed the issue.
