### ISSUE TITLE
Font Rendering

### ISSUE THREAD

**Issue by rextimmy** [ConfettiFX/The-Forge#39]
I noticed with the font rendering that vulkan is slightly blurry compared to d3d12. You can see in the screenshots below the green color is also slightly different between the two. Depending on what background color and font color, the difference can be really noticeable. If you save the two images below and quickly flick between them you will see the problem.

![d3d12](https://user-images.githubusercontent.com/4123979/38767821-29209624-402c-11e8-8c7c-f895843b7940.png)
![vulkan](https://user-images.githubusercontent.com/4123979/38767822-295419ae-402c-11e8-827d-ffa10d8050fa.png)

**Comment by manaskulkarni786** [comment]
Thanks for pointing this out. It should be fixed in the next release.
