### ISSUE TITLE
Any reason to require 10.13.3 for Macos?

### ISSUE THREAD

**Issue by oscarbg** [ConfettiFX/The-Forge#4]
Now 10.13.3 is stable but I have currently 10.13.2 installed..
can expect Metal 2 graphics driver bugs running 10.13.2?
would be nice to know what Metal2 bugs have been fixed in 10.13.3 anyway..

**Comment by wolfgangfengel** [comment]
It should run fine on 10.13.2. We just tested. Let us know if you bump into problems.

**Comment by oscarbg** [comment]
Ok.. just tested on 10.13.2 on a Vega 56 GPU..
all unit tests work (1-6) but is missing 07 tess sample, and 08 vs Windows (opened another separate issue BTW)..
Visibility Buffer sample doesn't work..
screenshot
![captura de pantalla 2018-01-26 a las 16 07 34](https://user-images.githubusercontent.com/669305/35445832-2d09de1e-02b3-11e8-9eec-24ea9e4e36bc.png)

log:
2018-01-26 16:04:35.167743+0100 Visibility_Buffer[10591:114447] [DYMTLInitPlatform] platform initialization successful
2018-01-26 16:04:35.272866+0100 Visibility_Buffer[10591:114405] Metal GPU Frame Capture Enabled
2018-01-26 16:04:35.273158+0100 Visibility_Buffer[10591:114405] Metal API Validation Enabled
Failed: (format <= ImageFormat::D32F)

File: /Users/oscarbarenysgarcia/The-Forge/Common_3/OS/Image/Image.cpp
Line: 380

Failed: (format <= ImageFormat::D32F)

File: /Users/oscarbarenysgarcia/The-Forge/Common_3/OS/Image/Image.cpp
Line: 380

Failed: (format <= ImageFormat::D32F)

File: /Users/oscarbarenysgarcia/The-Forge/Common_3/OS/Image/Image.cpp
Line: 380

2018-01-26 16:04:35.309591+0100 Visibility_Buffer[10591:114405] ../../../src/OSXMetal/visibilityBuffer_shade.metal Error Domain=MTLLibraryErrorDomain Code=4 "Compilation succeeded with: 

program_source:498:31: warning: comparison of integers of different signs: 'uint' (aka 'unsigned int') and 'int'
    if (alphaBit_drawID_triID != ~0)
        ~~~~~~~~~~~~~~~~~~~~~ ^  ~~
" UserInfo={NSLocalizedDescription=Compilation succeeded with: 

program_source:498:31: warning: comparison of integers of different signs: 'uint' (aka 'unsigned int') and 'int'
    if (alphaBit_drawID_triID != ~0)
        ~~~~~~~~~~~~~~~~~~~~~ ^  ~~
}
2018-01-26 16:04:35.309983+0100 Visibility_Buffer[10591:114405] ../../../src/OSXMetal/visibilityBuffer_shade.metal Error Domain=MTLLibraryErrorDomain Code=4 "Compilation succeeded with: 

program_source:498:31: warning: comparison of integers of different signs: 'uint' (aka 'unsigned int') and 'int'
    if (alphaBit_drawID_triID != ~0)
        ~~~~~~~~~~~~~~~~~~~~~ ^  ~~
" UserInfo={NSLocalizedDescription=Compilation succeeded with: 

program_source:498:31: warning: comparison of integers of different signs: 'uint' (aka 'unsigned int') and 'int'
    if (alphaBit_drawID_triID != ~0)
        ~~~~~~~~~~~~~~~~~~~~~ ^  ~~
}
2018-01-26 16:04:35.310770+0100 Visibility_Buffer[10591:114405] ../../../src/OSXMetal/visibilityBuffer_shade.metal Error Domain=MTLLibraryErrorDomain Code=4 "Compilation succeeded with: 

program_source:498:31: warning: comparison of integers of different signs: 'uint' (aka 'unsigned int') and 'int'
    if (alphaBit_drawID_triID != ~0)
        ~~~~~~~~~~~~~~~~~~~~~ ^  ~~
" UserInfo={NSLocalizedDescription=Compilation succeeded with: 

program_source:498:31: warning: comparison of integers of different signs: 'uint' (aka 'unsigned int') and 'int'
    if (alphaBit_drawID_triID != ~0)
        ~~~~~~~~~~~~~~~~~~~~~ ^  ~~
}
2018-01-26 16:04:35.311140+0100 Visibility_Buffer[10591:114405] ../../../src/OSXMetal/visibilityBuffer_shade.metal Error Domain=MTLLibraryErrorDomain Code=4 "Compilation succeeded with: 

program_source:498:31: warning: comparison of integers of different signs: 'uint' (aka 'unsigned int') and 'int'
    if (alphaBit_drawID_triID != ~0)
        ~~~~~~~~~~~~~~~~~~~~~ ^  ~~
" UserInfo={NSLocalizedDescription=Compilation succeeded with: 

program_source:498:31: warning: comparison of integers of different signs: 'uint' (aka 'unsigned int') and 'int'
    if (alphaBit_drawID_triID != ~0)
        ~~~~~~~~~~~~~~~~~~~~~ ^  ~~
}
INFO: [initApp] Load assimp scene : 3752.372070 msINFO: [initApp] Load assimp scene : 3752.372070 ms


INFO: [initApp] Load scene buffers : 765.911987 msINFO: [initApp] Load scene buffers : 765.911987 ms


INFO: [initApp] Load clusters : 1620.802979 msINFO: [initApp] Load clusters : 1620.802979 ms


-[MTLDebugBlitCommandEncoder validateCopyFromBuffer:sourceOffset:sourceBytesPerRow:sourceBytesPerImage:sourceSize:toTexture:destinationSlice:destinationLevel:destinationOrigin:options:]:456: failed assertion `destinationTexture must not be nil.'
(lldb)

**Comment by oscarbg** [comment]
must say I'm using Xcode 9.3 beta (so hope doesn't crash because that :-) )

**Comment by wolfgangfengel** [comment]
I am sorry we are not going to test for Vega 56 and Intel chips in the moment. Also please note that we do not have a hackintosh and probably will never get one ... so there is no way we can make sure it runs on your specific machine.
I will add on the Readme the machines we test on. If someone wants us to make sure it runs on a different machine, assuming there are problems, they will need to send us the Apple product :-)
We can only test on a subset of machines and we are trying to aim at the least common denominator.
We actually test on some Intel GPUs but they seem to have bugs in the driver, so we do not mention them as tested in the Readme.
