### ISSUE TITLE
Request: IRC, Gitter or Discord server (and question)

### ISSUE THREAD

**Issue by elviras9t** [ConfettiFX/The-Forge#49]
1. I want to request about any Q/A form, such as IRC, Gitter or Discord. Also, 
2. I have question: how can be implement another implementation of ray tracing, uses Vulkan API 1.1 compute shaders (and, probably, with `vulkan.hpp`) itself?

**Comment by wolfgangfengel** [comment]
Hi,
we have a skype channel that I can invite you too. Please send me your skype id via PM. It would be awesome if ray tracing with the Vulkan API 1.1 would be implemented in The Forge ... do you want to help with this?

**Comment by elviras9t** [comment]
Skype ID: elviras9t@gmail.com
About help with implementation, I considering about it. 
I have difficults with to make single command buffer ray tracer and BVH builder (i. e. my ray tracer in general based on direct calls).

**Comment by wolfgangfengel** [comment]
I sent you an invite.
