### ISSUE TITLE
1.01 release lacks Macos hardware tesselation test xcode project..

### ISSUE THREAD

**Issue by oscarbg** [ConfettiFX/The-Forge#5]
You say:
"Release 1.01 macOS now runs the Hardware Tessellation unit test. There is also now a new unit test that shows a procedurally generated earth."
but 07_Tessellation folder is missing OSXMetal subfolder unlike other tests and "macOS Xcode" folder is missing also "07_Tessellation"..
same applies to 08_Procedural sample is lacking OSXMetal subfolder and xcodeproj ..

**Comment by amsgames94** [comment]
Hi @oscarbg ,

Samples 07 and 08 were being internally tested on macOS and are now ready to go. There should be a new commit soon that adds them to the UnitTest workspace. Look forward to it!

**Comment by wolfgangfengel** [comment]
That should be fixed now. Can you close this issue?

**Comment by oscarbg** [comment]
Yes!
