### ISSUE TITLE
The-Forge as a plugin replacement

### ISSUE THREAD

**Issue by ZeroCrunch** [ConfettiFX/The-Forge#50]
This isn't an issue per se, but I was wondering how much effort would be involved in using The-Forge as a module in an existing game-engine-like framework.

If someone wanted to leverage the cross-platform rendering side of The-Forge but leave all the other bits behind.

**Comment by wolfgangfengel** [comment]
I am not sure I understand your question but in general the renderer interface in IRenderer.h was written with the intention to be used in custom game engines. So you would have to just implement those calls. There are a bunch of interfaces so that you can use your filesystem, memory manager, logger etc.. We use The Forge this way ...

**Comment by wolfgangfengel** [comment]
Let me know if you have any more questions. Assuming I understand your question correctly what you are asking for is what we use The Forge for.

**Comment by ZeroCrunch** [comment]
What I’m interested in using The-Forge has a disparate rendering library in an existing game-like framework. 

I’d like to ditch my current renderer library (self written) and use yours instead. 

Apologies for the tardy reply.

**Comment by manaskulkarni786** [comment]
Yes. That's completely possible. Currently, off the top of my head, the renderer uses some functionality from the Core library such as Thread synchronization primitives, Logging, File I/O. All these are used as interfaces which means you can create your own implementation for these interfaces using your game engine.
One simple example is we use conf_malloc / conf_calloc for memory allocations. These functions are declared in the interface IMemoryManager.h. So you will have to implement conf_malloc / conf_calloc somewhere in your engine. Same goes for the File, Thread, Mutex classes. You can take a look at all the interface files. They are located in Common_3/OS/Interfaces/
Other than that we use tinystl for containers.

**Comment by ZeroCrunch** [comment]
Great! Thank you!
