### ISSUE TITLE
getUSec function in WindowsBase.cpp seem buggy

### ISSUE THREAD

**Issue by rbourianes** [ConfettiFX/The-Forge#56]
getUSec() and getMSec() functions seem to be used using the following code :
`double millisec = (double)getMSec() / (double)getTimerFrequency()`
`double microsec = (double)getUSec() / (double)getTimerFrequency()`

If that's correct I believe getUSec should return `return curr.QuadPart * (int64_t)1e6;` instead of `return counter.QuadPart;`
getMSec code is in line with the assumed usage.

**Comment by manaskulkarni786** [comment]
It should be fixed in the next release and also account for the timer frequency
`return curr.QuadPart * (int64_t)1e6 / getTimerFrequency();`

**Comment by wolfgangfengel** [comment]
fixed. Let us know if it works for you.
