### ISSUE TITLE
Toggling fullscreen not handled

### ISSUE THREAD

**Issue by tksuoran** [ConfettiFX/The-Forge#6]
On Windows 10, I pressed alt-enter to toggle fullscreen.
vkAcquireNextImageKHR() returned VK_ERROR_OUT_OF_DATE_KHR.
This triggered assert in Vulkan.cpp:3740:
ASSERT(VK_SUCCESS == vk_res);

**Comment by wolfgangfengel** [comment]
Works on NVIDIA / AMD. What hardware are you running?

**Comment by tksuoran** [comment]
NVIDIA. Here is begin of info dumped by vkjson_info.exe:
"apiVersion":	4194360,
"driverVersion":	1627602944,
"vendorID":	4318,
"deviceID":	7171,
"deviceType":	2,
"deviceName":	"GeForce GTX 1060 6GB",

**Comment by wolfgangfengel** [comment]
You have the latest driver and you see this in all unit tests and the example?

**Comment by tksuoran** [comment]
Current driver version 388.12, so not quite latest. I get the same issue consistently with all examples. I am downloading latest driver and will report results later.

**Comment by tksuoran** [comment]
Reproduces the same with 390.65.

**Comment by manaskulkarni786** [comment]
Hey @tksuoran, this seems to be happening on some machines. Expect a fix soon. Thanks

**Comment by wolfgangfengel** [comment]
That should be fixed now. Can you close this issue?
