### ISSUE TITLE
Can't run any Mac unit tests or visibility buffer..

### ISSUE THREAD

**Issue by oscarbg** [ConfettiFX/The-Forge#64]
Hi,
testing the forge 1.13 samples and run fine compiled with Xcode 10 beta 4 on IOS 12.0 beta 4..
but using exact Xcode on Mac 10.13.6 I get lots of this error:

> xcrun: error: unable to find utility "metal", not a developer tool or in PATH

any help is appreciated..

full log for visibility buffer:

> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/shadow_pass.vert.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader shadow_pass.vertxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/shadow_pass_alpha.vert.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader shadow_pass_alpha.vertxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/visibilityBuffer_pass.vert.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader visibilityBuffer_pass.vertxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/visibilityBuffer_pass_alpha.vert.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader visibilityBuffer_pass_alpha.vertxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/visibilityBuffer_shade.vert.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader visibilityBuffer_shade.vertxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/visibilityBuffer_shade.vert.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader visibilityBuffer_shade.vertxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/deferred_pass.vert.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader deferred_pass.vertxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/deferred_pass.vert.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader deferred_pass.vertxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/deferred_shade.vert.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader deferred_shade.vertxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/deferred_shade.vert.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader deferred_shade.vertxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/deferred_shade_pointlight.vert.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader deferred_shade_pointlight.vertxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/clear_buffers.comp.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader clear_buffers.compxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/triangle_filtering.comp.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader triangle_filtering.compxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/clear_light_clusters.comp.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader clear_light_clusters.compxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/cluster_lights.comp.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader cluster_lights.compxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/HDAO.vert.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader HDAO.vertxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/HDAO.vert.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader HDAO.vertxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/HDAO.vert.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader HDAO.vertxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/HDAO.vert.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader HDAO.vertxcrun: error: unable to find utility "metal", not a developer tool or in PATH
> Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1114)	Failed to compile shader ../../../src/OSXMetal/resolve.vert.metalError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader resolve.vertINFO: [Init] Load shaders : 458.811005 ms
> 
> 
> INFO: [Init] Load assimp scene : 5166.097168 ms
> 
> 
> INFO: [Init] Load scene buffers : 1093.048950 ms
> 
> 
> INFO: [Init] Load clusters : 1613.715942 ms
> 
> 
> INFO: [Init] Load textures : 578.322021 ms

**Comment by oscarbg** [comment]
Ok sorry that was an error fixed with "xcode-select" to point to current Xcode beta location..
but now I get (other sample)

```
2018-07-28 13:48:29.729487+0200 02_Compute[6524:89118] [DYMTLInitPlatform] platform initialization successful
INFO: Opened log file /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Examples_3/Unit_Tests/macOS Xcode/Bin/Debug/02_Compute/Log.log


2018-07-28 13:48:29.907885+0200 02_Compute[6524:89031] Metal GPU Frame Capture Enabled
2018-07-28 13:48:29.908191+0200 02_Compute[6524:89031] Metal API Validation Enabled
2018-07-28 13:48:30.411707+0200 system_profiler[6527:89198] Metal API Validation Enabled
INFO: [initRenderer] Current Gpu Name: AMD Radeon RX Vega 56


INFO: [initRenderer] Current Gpu Vendor ID: 0x1002


INFO: [initRenderer] Current Gpu Model ID: 0x687f


2018-07-28 13:48:31.383969+0200 xcodebuild[6530:89218] [] Failed to read clone map from disk: The file “device_map.plist” couldn’t be opened because there is no such file.
metallib: Invalid bitcode file!
Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1112)	Failed to assemble shader's ../../../src/02_Compute/OSXMetal/display.vert.metal .metallib fileError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader display.vertmetallib: Invalid bitcode file!
Error: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1112)	Failed to assemble shader's ../../../src/02_Compute/OSXMetal/compute.comp.metal .metallib fileError: /Users/oscarbarenysgarcia/Downloads/The-Forge-1.13/Common_3/Renderer/ResourceLoader.cpp(1307)	Error while generating bytecode for shader compute.comp
```

**Comment by wolfgangfengel** [comment]
As you mentioned already, one thing I found with the latest XCode 10.0 beta 4 (10L213o) is that I have to xcode-select the command line tools. It seems like they are not pre-selected. This entry was empty for me.
What I had to do was I had to go to Xcode -> Preferences -> Locations -> then select Xcode 10.0 here. You probably have to sign in to make that selection.
From what I hear from my colleague there are also some code changes necessary to make that work. We are going to push those to github as soon as we have them ready and tested.

**Comment by AntoineConffx** [comment]
@oscarbg 
This should be fixed now.
Could you confirm the issue is fixed?
Thanks

**Comment by oscarbg** [comment]
thanks issue is fixed now!

seems like it needed it needs running metal command with:
args.push_back("-c");

also unrelated exploring your code learned how vsync is disabled on Metal:

(*pSwapchain)->pMTKView.enableSetNeedsDisplay = YES;
(*pSwapchain)->pMTKView.paused = YES;
