### ISSUE TITLE
How can I add The Forge as a dependecy?

### ISSUE THREAD

**Issue by IgrauBezRuk** [ConfettiFX/The-Forge#66]
Hey! I have a question about The Forge configuration.
You have an examples, but in examples, you connect libraries directly to solution. How can I add libraries as a submodule to my project?

**Comment by wolfgangfengel** [comment]
What problem are you trying to solve when you think of making it a submodule? You might want to try to make it a DLL or static library to make that work for you?

**Comment by IgrauBezRuk** [comment]
I want The Forge as main renderer for all of my graphics R&D projects so there multiple problems. 
First, I want to keep my repository clean from external code.
Second, I want to have The Forge always up to date, with git submodule update I will get last commits.
Third, I don't want to configure solution to regenerate static library each time.
Perfect decision is to remove every build system you have and have one cmake.
And this can be something like : In my CMakeListst.txt
include_directories(${THE_FORGE_INCLUDE_DIR})
add_libraries(${THE_FORGE_LIBRARY}) and then
Download repository -> Download The Forge as a submodule -> compile and link.

Also I have experience with CMake and I can contribute.

**Comment by wolfgangfengel** [comment]
I suggest you use a static library.
