### ISSUE TITLE
Question: Vulkan raytracing support planned?

### ISSUE THREAD

**Issue by oscarbg** [ConfettiFX/The-Forge#69]
Hi,
just read about Nsight graphics update at Siggraph with Vulkan raytracing support (altough no drivers yet) and seeing you support already DXR wanted to ask if you plan to support Vulkan raytrace in the Forge in addition to DXR..
better yet (and seeing http://confettishadertranslator.azurewebsites.net) would be if you can support translation from DXR HLSL shaders to Vulkan GLSL raytrace extensions (yet to be published) so from one shader we are able to target Vulkan too..
Have a Volta card to test once Vulkan drivers are out..

thanks..

**Comment by wolfgangfengel** [comment]
Hey Oscar, 
I think we have that on our list. Thanks for the offer to beta test :-) This is very much appreciated. Does the current Ray Tracing unit tests all work on your card?

- Wolfgang

**Comment by oscarbg** [comment]
Hi,
tested, but it doen't count as I'm currently running an insider build and seems all DXR content crashes..
gonna clean an SSD to install supported RS4 and report results..

**Comment by wolfgangfengel** [comment]
Yep it is in there since two releases :-)
