### ISSUE TITLE
Visibility Buffer crashes on Vega 56 on Macos 10.13.2

### ISSUE THREAD

**Issue by oscarbg** [ConfettiFX/The-Forge#7]
just opening here for visibility: 
Vega 56 Macos 10.13.2 Xcode 9.3 beta
https://github.com/ConfettiFX/The-Forge/issues/4#issuecomment-360809678

**Comment by amsgames94** [comment]
It looks like, for some reason, the renderer is failing to allocate a MTLTexture to hold one of the scene's textures. I assume you've downloaded the art assets before building the SanMiguel scene, right? (running "./PRE_BUILD.sh" from the terminal). If you have, could you please provide some more details on your machine?

**Comment by oscarbg** [comment]
of course downloaded the assets with /PRE_BUILD.sh and seems extracted correctly..
It's a hackintosh Skylake 6600k with Vega 56 but that shouldn't make a difference..

**Comment by oscarbg** [comment]
updated to 10.13.4beta and started from scratch: redownloaded project and run pre_build.sh which downloaded and unzipped Art.zip.. still same bug..

**Comment by wolfgangfengel** [comment]
I am sorry we are not going to test for Vega 56 and Intel chips in the moment. Also please note that we do not have a hackintosh and probably will never get one ... so there is no way we can make sure it runs on your specific machine.
I will add on the Readme the machines we test on. If someone wants us to make sure it runs on a different machine, assuming there are problems, they will need to send us the Apple product :-)
We can only test on a subset of machines and we are trying to aim at the least common denominator.
We actually test on some Intel GPUs but they seem to have bugs in the driver, so we do not mention them as tested in the Readme.
