### ISSUE TITLE
Memory aliasing

### ISSUE THREAD

**Issue by jdswebb** [ConfettiFX/The-Forge#72]
I've been considering switching my DX12-only project to using the The-Forge. I've already done a simple conversion which went pretty smoothly and seems to work well. Some feedback on the conversion in case it's useful to you:

- I had some class name collisions due to The-Forge not using namespaces or some kind of class prefix.
- The use of a #define for PI also caused a problem.
- Options like NO_GAINPUT should maybe be the default. I expect I'm not going to be alone in just wanting the core rendering capabilities as described in the readme and not so much of the utility code also provided. Even just some advice in the readme on how to include the minimum for rendering would have been useful.

I'm interested to know if there any way to support memory/resource aliasing in The-Forge? In my current DX12 implementation I know the lifetimes of transient resources over a frame and so I've made use of memory aliasing to reduce the total amount of memory allocated. It's not clear to me how to do anything like this with The-Forge - I might be missing something.

Many thanks!

**Comment by jdswebb** [comment]
Thanks for the reply! Sorry about the delay getting back to you, I've not had a chance to touch this for a while.

_"if you take the folder "Renderer" and the IRenderer.h interface, that should give you the barebone rendering part."_

That's what I tried to start with though I had to include the OS folder and I think some others as well. I ended up making a fork just to make things a bit easier for integration. It's very specific to my use case, but in case it's useful to know how people are using The-Forge this is what I did:

- Put The-Forge code in a namespace as I had a couple of collisions by default.
- Replace OS/* header usage with implementations I already had in my project. This worked out for the best anyway as I don't think it's desirable to have multiple logging/allocation/job systems in a project.

After doing that I more or less achieved what I wanted and could just use the Renderer+tinystl headers.

One other thing I'm curious about is whether there is any documentation on how heap allocation is handled and what level of user control there is over it. One thing I need to do in my project is create 8192 small (64x64) textures. From the DX12 documentation it seems like this would be a good opportunity to used placed resources to lower the runtime (and maybe memory) costs of creating these textures. Can I get The-Forge to do this for me? I realise there may be better solutions to this particular problem like just partitioning a single larger texture or texture arrays, but I'm still generally curious about this aspect of The-Forge.

I'd be happy to join a discussion group but I know very little about this stuff so I'm not sure how much I could offer! :)

**Comment by manaskulkarni786** [comment]
By default, the Forge D3D12 memory manager will create these textures as placed resources from heaps of size 64 MB / 16 MB. But there is no support for memory aliasing for the PC implementation. You can find the interface here.
[https://github.com/ConfettiFX/The-Forge/blob/master/Common_3/Renderer/Direct3D12/Direct3D12MemoryAllocator.h](url)

**Comment by jdswebb** [comment]
Thanks - I expect for my usage then the 8k textures would get split across two heaps. That should be fine, I was only concerned if each texture was going to be created as a committed resource.

**Comment by wolfgangfengel** [comment]
Can we close this then?
