### ISSUE TITLE
Any documentation available?

### ISSUE THREAD

**Issue by fcvarela** [ConfettiFX/The-Forge#77]
Forgive me if I’m being thick but I can’t find any doc references in the repo, wiki. Are there any docs available somewhere?

**Comment by wolfgangfengel** [comment]
There is a documentation in the documentation folder that describes how we utilize math. There is a blog post for the Visibility Buffer. Occasionally there is some documentation for unit tests.
Regarding all the code that uses graphics API calls, you want to use the documentation that comes with the graphics API. After all, it is a rendering framework and graphics API calls are the majority of the code.
If you want to write any other documentation, contact me via PM.

**Comment by wolfgangfengel** [comment]
I started working on an introductory slide deck that should help people do their first steps. If you want to proof-read that, let me know.

**Comment by fcvarela** [comment]
I’d love to, yes please!
