### ISSUE TITLE
Support for "Adaptive Order Independent Transparency with Raster Order Views" on Metal 2?

### ISSUE THREAD

**Issue by oscarbg** [ConfettiFX/The-Forge#78]
Hi,
just tested these "new transparency sample" on Windows.. Raster Order Groups mode works OK on DX API..
doing a quick test on Vega of these sample on Macos seems the Raster Order View variant (Intel paper) is missing on Macos altough Metal2 supports "Raster Order Groups"..
As you probably know Raster Order Groups is an optional feature of Metal2 but it's implemented on Vega Metal2 driver, as it shows :
areRasterOrderGroupsSupported 1
so are you planning to implement Raster order group support on the transparency sample on Macos?
would be nice as there aren't many (if any) samples of using Raster Order Groups on Metal..
also note I opened some time ago an issue requesting exposing Raster order groups in Vulkan:
https://github.com/KhronosGroup/Vulkan-Ecosystem/issues/27
so hope eventually it's exposed and transparency AOIT mode can be supported also on Vulkan..
thanks..

**Comment by oscarbg** [comment]
Hi Antoine,
nice.. wasn't aware that there weren't also any wave intrinsics Metal samples..
good to know interested in giving a look on ROV on Metal.. as there are some Apple provided samples but they seem all IOS only and targeted towards showing new A11 chip features and using also things like imageblocks.. so not directly portable to MacOS without some thought..
thanks..

**Comment by oscarbg** [comment]
Hi,
just pointing out that VK_EXT_fragment_shader_interlock is available so a ROV sample could be supported now on all APIs (D3D12,VUlkan,Metal2)

**Comment by manaskulkarni786** [comment]
ROV sample now supported on D3D12, Vulkan.

**Comment by wolfgangfengel** [comment]
Can we close it then?
