### ISSUE TITLE
Can not transition non-pixel shader resource to pixel shader resource

### ISSUE THREAD

**Issue by jdswebb** [ConfettiFX/The-Forge#84]
Hi,

I'm having an issue as per the title, I get the following error:

D3D12 ERROR: CGraphicsCommandList::SetGraphicsRootDescriptorTable: Resource state (0x40: D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE) of resource (0x000001ABA44DC580:'SceneDepth') (subresource: 0) is invalid for use as a PIXEL_SHADER_RESOURCE.  Expected State Bits (all): 0x80: D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE, Actual State: 0x40: D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE, Missing State: 0x80: D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE. This validation is being enforced at bind during command list recording because the descriptor for this resource in the root signature is declared as DATA_STATIC_WHILE_SET_AT_EXECUTE. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]

I've called cmdResourceBarrier appropriately beforehand but it does not actually do anything due to this line:

if (!(pTexture->mCurrentState & pTransBarrier->mNewState) && pTexture->mCurrentState != pTransBarrier->mNewState)

with:

pTexture->mCurrentState = RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE (64)
pTransBarrier->mNewState = RESOURCE_STATE_SHADER_RESOURCE (192)

so the first part of the if statement is false.

Thanks

**Comment by jdswebb** [comment]
I've worked around this by changing the ResourceState definition to just '	RESOURCE_STATE_SHADER_RESOURCE = 0x80' but I'm sure it had its previous value for a reason and this is the wrong solution.

**Comment by wolfgangfengel** [comment]
Should be fixed with the last release. Let us know.

**Comment by jdswebb** [comment]
Seems good - thanks!
