### ISSUE TITLE
07 Tesselation Macos sample fails on both Vega 56 and Intel HD 530..

### ISSUE THREAD

**Issue by oscarbg** [ConfettiFX/The-Forge#9]
applied your pull request and procedural sample works but tesselation sample fails with..

2018-01-27 14:56:31.843688+0100 07_Tessellation[820:9349] validateFunctionStepRate, line 301: error 'MTLVertexStepFunctionPerVertex not allowed with postTessellationVertexFunction.'
validateFunctionStepRate:301: failed assertion `MTLVertexStepFunctionPerVertex not allowed with postTessellationVertexFunction.'
(lldb) 

![captura de pantalla 2018-01-27 a las 14 57 11](https://user-images.githubusercontent.com/669305/35472622-d94d6c3a-0372-11e8-9870-c8372de6f223.png)

**Comment by oscarbg** [comment]
just pointing out updating to Macos 10.13.4 beta 1 which ships with newer drivers still hits the same bug..
maybe because using Xcode 9.3 beta?

**Comment by wolfgangfengel** [comment]
I am sorry we are not going to test for Vega 56 and Intel chips in the moment. Also please note that we do not have a hackintosh and probably will never get one ... so there is no way we can make sure it runs on your specific machine. 
I will add on the Readme the machines we test on. If someone wants us to make sure it runs on a different machine, assuming there are problems, they will need to send us the Apple product :-) 
We can only test on a subset of machines and we are trying to aim at the least common denominator.
We actually test on some Intel GPUs but they seem to have bugs in the driver, so we do not mention them as tested in the Readme.
