### ISSUE TITLE
Will you be supporting MESA + RADV eventually?

### ISSUE THREAD

**Issue by rdeleonp** [ConfettiFX/The-Forge#91]
Hi.

For PC Linux Requirements, you mention support for AMDGPU-Pro.

Just wanted to know if you'll be supporting MESA + RADV eventually.

Thanks for your time.

Cheers.

**Comment by wolfgangfengel** [comment]
We would like to. Do you want to add support?

**Comment by rdeleonp** [comment]
Hi.

Thanks for the reply.

I'm not a game/graphics dev, was just curious if support was possible, because [MESA + RADV is being pushed heavily by Valve](https://www.phoronix.com/scan.php?page=news_item&px=Daniel-Joins-Valve-Driver), both to help to advance game development on Linux, and for the [Proton](/ValveSoftware/Proton) project _(some people suspect this may be a sign of [new Steam Machines](https://steamcommunity.com/groups/steamuniverse/discussions/1/1742230617618733711/))_.

Just for reference, the [DXVK team](/doitsujin/dxvk) _(Proton dependency)_ support both [RADV and AMDGPU-Pro](/doitsujin/dxvk/wiki/Driver-support); maybe perusing their repo could help you guys in some way.

If that's too much effort, maybe revisit this item later on.

Thanks for your time.

Cheers.

**Comment by boberfly** [comment]
Hi @rdeleonp 
I can test this for you as I run RADV on my workstation. I did try the Linux build before but I think I had another issue as the nvidia card wasn't working either. I'll update this when I get it to work.

Cheers

**Comment by boberfly** [comment]
![screenshot_20190219_230135](https://user-images.githubusercontent.com/5601445/53072594-6ecc4700-349a-11e9-94ab-092aae33f740.png)
This is running on RADV, looks like it is working fine...

**Comment by wolfgangfengel** [comment]
Hey Alex, awesome! were you also able to test the others? To support something like RADV we will have to have a test setup in the office that is integrated into our automatic test setup. In case all this works, we can consider adding another machine for testing.

**Comment by boberfly** [comment]
Hi @wolfgangfengel 
I've only got one of the example tests integrated into The-Forge-Lite but I can get the others to work too, so not quite yet. I've not tried this but I believe the AMD drivers all can sit with each other on the one system if you wanted to use the same Linux system, they tap into the same kernel module and just have different user-space libs.

**Comment by wolfgangfengel** [comment]
@boberfly I think we can close this. You are running with RADV since a while?

**Comment by wolfgangfengel** [comment]
Thinking about this: we shouldn't setup another Linux machine with the MESA + RADV drivers for our test environment. This slowly spins out of control. The main exception would be that a customer would need it but then we probably would give up support of other drivers.

**Comment by boberfly** [comment]
Hey @wolfgangfengel 
I don't mind testing and submitting patches back here if it's out of scope of the unit tests. Like I mentioned in the other issue, I guess one big reason at least for the future might be that Intel's official ANV driver will most likely be the one found in Mesa, and that SteamOS uses RADV. Not sure about Stadia though...

**Comment by OvermindDL1** [comment]
I've also heard the AMDGPU-PRO drivers are essentially deprecated, MESA is the way to go for AMD officially.  The AMDGPU-PRO drivers only still exist for a couple of non-game-related proprietary things that are being phased out, and beyond those the capabilities (especially in regards to vulkan) should be identical between AMDGPU-PRO and MESA (with reports of AMDGPU-PRO falling behind now).
