### ISSUE TITLE
Question: The Forge is an low-level rendering framework?

### ISSUE THREAD

**Issue by hydexon** [ConfettiFX/The-Forge#99]
Hi, i just discovered The Forge framework could be a nice library for my starting project and i need to search an a good long-term stack, i'm around The Forge library or bs::framework, and empirically i saw some details compared with bs::framework, Seems the renderer itself is really low-level, the renderer is mostly C-style functions and pointers, and the engine build system is crude but simplistic making it easy to replace with my own, unlike bsf, which needs a lot of tunning and heavy modifications.

I like you try to avoid to use the Standard STL with TinySTL. Also i'm aiming to background resource loading (textures, meshes, etc) and how feasible will be task scheduling for gameplay, rendering, and other middleware (Audio, AI, etc).

There's concept of Technique, Materials and Pass?, otherwise they can be implemented easily as an high-level layer with the APIs provided by the framework?

Thanks.

**Comment by wolfgangfengel** [comment]
The Forge is the rendering layer of a game engine and is used as such. You can build lots of things on top of it. There is no fixed concept of technique, material or pass but we might add this in the near future. For our internal projects we have those implemented. We need to see if and how we implement this in The Forge. Maybe we start a dedicated repository for this or add it to The Forge.

**Comment by hydexon** [comment]
> There is no fixed concept of technique, material or pass but we might add this in the near future
So it can be somewhat trivial implement one at my own?

**Comment by wolfgangfengel** [comment]
It should be.

**Comment by jdswebb** [comment]
> There is no fixed concept of technique, material or pass but we might add this in the near future. For our internal projects we have those implemented. We need to see if and how we implement this in The Forge. Maybe we start a dedicated repository for this or add it to The Forge.

Reference implementations of this kind of thing would be very useful in my opinion - I think the dedicated repository would be better.
